// GENERATED by scripts/build-catalog.mjs from public/films.txt and
// public/artists.txt — do not hand-edit. scripts/check-catalogs.mjs
// re-derives these sets from the committed catalogues and fails CI on
// any disagreement, in ci.yml and backend-checks.yml both.
//
// The trigger validates catalog `entity` keys against these sets
// (functions/src/v2.ts, CATALOG_DOMAINS): an empty set means the
// domain's catalogue has not been generated yet, so nothing
// aggregates for it — fail-safe until an operator runs the builder
// (D15 records why generation is an operator step).
export const FILM_KEYS: ReadonlySet<number> = new Set<number>();
export const ARTIST_KEYS: ReadonlySet<number> = new Set<number>();
