// life-age-facts.tsx — the "what's particular about this age" card
// in LifeOverlay's age tab. Previously a hand-typed array of 5
// literary observations tied to age 34. Now generated by Gemma
// on-device with the user's real age.
//
// Cached per-age in localStorage so reopening the overlay doesn't
// regenerate. "↻ again" regenerates explicitly. When the LLM isn't
// available (web build) the card explains why.

import { useEffect, useRef, useState } from "react";
import { Kicker } from "../shared/primitives";
import { useLLM } from "../../lib/useLLM";

interface Fact {
  kicker: string;
  body: string;
}

const FACT_GLYPHS = ["✦", "◐", "☾", "✶", "↑"];

// Parse the Gemma output into 5 (kicker, body) pairs. We ask the
// model to format as numbered items with bold kickers; in practice
// small models drift. We're lenient.
//
// Accepted forms:
//   "1. biology: Your prefrontal cortex…"
//   "1. **biology** — Your prefrontal…"
//   "1) biology — Your prefrontal…"
//   "biology: Your prefrontal…"   (no leading number)
// On failure we drop to a single-card fallback so the section is
// never broken.
function parseFacts(raw: string): Fact[] {
  const out: Fact[] = [];
  const lines = raw
    .split(/\n+/)
    .map((l) => l.trim())
    .filter(Boolean);
  for (const line of lines) {
    // Strip "1." / "1)" / "- " prefixes
    let s = line.replace(/^[*-]\s*/, "");
    s = s.replace(/^\d+[.)]\s*/, "");
    // Strip wrapping bold or quotes
    s = s.replace(/\*\*/g, "");
    s = s.replace(/^["']+|["']+$/g, "");
    // Split on the first colon / em-dash / en-dash
    const m = s.match(/^([^:—–]+?)\s*[:—–]\s*(.+)$/);
    if (m) {
      const kicker = m[1].trim().toLowerCase();
      const body = m[2].trim();
      if (kicker && body && kicker.length < 40 && body.length > 8) {
        out.push({ kicker, body });
        if (out.length === 5) break;
      }
    }
  }
  // Fallback: one big "facts" card containing the whole text.
  if (out.length === 0 && raw.trim()) {
    out.push({ kicker: "facts", body: raw.trim() });
  }
  return out;
}

function promptFor(age: number): string {
  return [
    `You are a quiet journal companion. The user is ${age} years old.`,
    `Write five short, literary observations about being ${age} — one per line — covering different angles:`,
    `1. biology — what's happening in the body and brain at this age`,
    `2. statistically — where this age sits in a population`,
    `3. historically — who was famous for what they did at this age, or a cultural note`,
    `4. numerically — something interesting about the number itself (Fibonacci, primes, century points, etc.)`,
    `5. in a lifetime — what this age tends to mean as a chapter`,
    ``,
    `Each line: a short lowercase kicker, then "—" or ":", then 1-2 sentences.`,
    `Be observational and slightly poetic — no advice, no cheer, no "you should". Examples:`,
    `1. biology — Cartilage in the long bones has finished closing; the body settles into its adult frame.`,
    `2. statistically — You are older than roughly half the people alive on Earth.`,
    `Output exactly five lines.`,
  ].join("\n");
}

const cacheKey = (age: number) => `insight.agefacts.${age}.v1`;

export function AgeFactsSection({ age }: { age: number }) {
  const { available, ready, downloading, downloadPct, error, ensure, generate } =
    useLLM();
  const [facts, setFacts] = useState<Fact[] | null>(() => {
    try {
      const raw = localStorage.getItem(cacheKey(age));
      return raw ? (JSON.parse(raw) as Fact[]) : null;
    } catch {
      return null;
    }
  });
  const [generating, setGenerating] = useState(false);
  const startedRef = useRef(false);

  // Reset when age changes (which happens around the user's
  // birthday). Re-read cache for the new age.
  useEffect(() => {
    try {
      const raw = localStorage.getItem(cacheKey(age));
      setFacts(raw ? (JSON.parse(raw) as Fact[]) : null);
    } catch {
      setFacts(null);
    }
    startedRef.current = false;
  }, [age]);

  useEffect(() => {
    if (!available || !ready) return;
    if (facts) return;
    if (startedRef.current) return;
    startedRef.current = true;
    void run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [available, ready, facts]);

  const run = async () => {
    setGenerating(true);
    try {
      if (!ready) await ensure();
      const text = await generate(promptFor(age));
      const parsed = parseFacts(text);
      if (parsed.length > 0) {
        setFacts(parsed);
        try {
          localStorage.setItem(cacheKey(age), JSON.stringify(parsed));
        } catch {
          // ignore quota errors — facts still show for this session
        }
      }
    } catch (err) {
      console.error("[AgeFacts] generation failed:", err);
    } finally {
      setGenerating(false);
    }
  };

  const regenerate = () => {
    setFacts(null);
    startedRef.current = true;
    void run();
  };

  return (
    <>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "baseline",
        }}
      >
        <Kicker>what's particular about this age</Kicker>
        {available && ready && !generating && facts && (
          <span
            onClick={regenerate}
            style={{
              fontFamily: "var(--mono)",
              fontSize: 9,
              letterSpacing: "0.1em",
              color: "var(--ink-3)",
              cursor: "pointer",
            }}
          >
            ↻ AGAIN
          </span>
        )}
      </div>

      {facts && !generating && (
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 8,
            marginTop: 10,
          }}
        >
          {facts.map((f, i) => (
            <div
              key={i}
              className="card"
              style={{ padding: 12, display: "flex", gap: 12 }}
            >
              <div
                style={{
                  width: 30,
                  height: 30,
                  borderRadius: "50%",
                  background: "var(--paper)",
                  border: "0.5px solid var(--rule)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                  fontFamily: "var(--serif)",
                  color: "var(--accent)",
                  fontSize: 15,
                }}
              >
                {FACT_GLYPHS[i % FACT_GLYPHS.length]}
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div className="kicker">{f.kicker}</div>
                <div
                  style={{
                    fontFamily: "var(--serif)",
                    fontSize: 13.5,
                    marginTop: 4,
                    lineHeight: 1.4,
                  }}
                >
                  {f.body}
                </div>
              </div>
            </div>
          ))}
          <div
            className="margin-note"
            style={{
              marginTop: 4,
              fontSize: 10,
              textAlign: "center",
              color: "var(--ink-3)",
              fontFamily: "var(--mono)",
              letterSpacing: "0.1em",
            }}
          >
            ON-DEVICE · GEMMA · NEVER LEAVES YOUR PHONE
          </div>
        </div>
      )}

      {generating && (
        <div
          className="card"
          style={{ marginTop: 10, padding: 14, borderLeft: "3px solid var(--accent)" }}
        >
          <div className="kicker">ON-DEVICE · GENERATING</div>
          <div
            style={{
              fontFamily: "var(--serif)",
              fontStyle: "italic",
              fontSize: 14,
              color: "var(--ink-3)",
              marginTop: 6,
            }}
          >
            five observations about being {age}…
          </div>
        </div>
      )}

      {!available && (
        <div
          className="card"
          style={{
            marginTop: 10,
            padding: 14,
            borderLeft: "3px solid var(--ink-3)",
          }}
        >
          <Kicker>on-device only</Kicker>
          <div className="margin-note" style={{ marginTop: 6, fontSize: 12 }}>
            "Reflections on this age are generated on-device by Gemma —
            they only work in the iOS / Android app. Open it there to
            see five observations for being {age}."
          </div>
        </div>
      )}

      {available && !ready && !downloading && !facts && !generating && (
        <div
          className="card"
          style={{
            marginTop: 10,
            padding: 14,
            borderLeft: "3px solid var(--accent)",
          }}
        >
          <Kicker>download the model</Kicker>
          <div className="margin-note" style={{ marginTop: 6, fontSize: 12 }}>
            Five observations for being {age}, generated entirely on your
            phone. First time uses ~2 GB; after that it's offline and
            instant.
          </div>
          <button
            type="button"
            onClick={() => void ensure()}
            style={{
              marginTop: 10,
              padding: "8px 14px",
              background: "var(--ink)",
              color: "var(--paper)",
              border: "none",
              borderRadius: 99,
              fontFamily: "var(--mono)",
              fontSize: 10,
              letterSpacing: "0.12em",
              cursor: "pointer",
            }}
          >
            ↓ DOWNLOAD AI · ~2 GB
          </button>
        </div>
      )}

      {downloading && (
        <div
          className="card"
          style={{
            marginTop: 10,
            padding: 14,
            borderLeft: "3px solid var(--accent)",
          }}
        >
          <div className="kicker">DOWNLOADING · {downloadPct}%</div>
          <div
            style={{
              height: 4,
              background: "var(--paper-3)",
              borderRadius: 999,
              overflow: "hidden",
              marginTop: 6,
            }}
          >
            <div
              style={{
                height: "100%",
                width: `${downloadPct}%`,
                background: "var(--accent)",
                transition: "width 0.2s",
              }}
            />
          </div>
        </div>
      )}

      {error && !generating && !facts && (
        <div
          className="margin-note"
          style={{
            fontSize: 11,
            color: "oklch(0.55 0.16 12)",
            marginTop: 8,
          }}
        >
          {error}
        </div>
      )}
    </>
  );
}
