// elements.ts — the periodic-table catalogue behind the feed's `pick` card
// (docs/CATALOG-QUESTIONS.md: a favourite is one pick from a shipped
// catalogue, and the stored answer is the entry's KEY, never a string).
//
// The pokedex.ts contract with the nouns swapped: the asset is
// public/elements.txt (`z<TAB>Name (Symbol)`, generated by
// scripts/build-elements.mjs, drift-gated by scripts/check-elements.mjs),
// the key is the atomic number, and the display name is resolved from the
// key at render time — store the key, display the name.

export interface Element {
  /** Atomic number — the stored answer key. */
  z: number;
  /** Display name, symbol included: "Gold (Au)". */
  name: string;
}

// "Not listed" answers store this instead of an atomic number. It is a real
// bucket in the reveal (published as a count, never enumerated) and 0 is
// unused by the catalogue, so the whole answer domain stays one integer.
export const NOT_LISTED = 0;

// ── loading ────────────────────────────────────────────────────────────

let cache: Element[] | null = null;
let inflight: Promise<Element[]> | null = null;

export function parseElements(text: string): Element[] {
  const out: Element[] = [];
  for (const line of text.split("\n")) {
    if (!line || line.charCodeAt(0) === 35 /* # */) continue;
    const tab = line.indexOf("\t");
    if (tab < 1) continue;
    const z = Number(line.slice(0, tab));
    const name = line.slice(tab + 1);
    // A non-integer key or an empty name is a file this parser does not
    // know. check-elements.mjs makes sure this never fires on the shipped
    // file — being lenient here would mean resolving answers against a
    // half-understood catalogue.
    if (!Number.isInteger(z) || z < 1 || !name) continue;
    out.push({ z, name });
  }
  return out;
}

/**
 * Load the catalogue. Concurrent callers share one fetch; a failed load is
 * not cached, so opening the picker again retries.
 */
export function loadElements(): Promise<Element[]> {
  if (cache) return Promise.resolve(cache);
  if (inflight) return inflight;
  // BASE_URL, not a bare "/elements.txt" — the places.ts argument: Capacitor
  // shells and subpath deploys do not serve the bundle from "/".
  const url = `${import.meta.env.BASE_URL || "/"}elements.txt`.replace(/\/{2,}/g, "/");
  inflight = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`elements.txt: HTTP ${r.status}`);
      return r.text();
    })
    .then((text) => {
      const elements = parseElements(text);
      // Zero entries means the fetch succeeded against something that is
      // not the catalogue — a SPA index.html fallback, most likely.
      if (!elements.length) throw new Error("elements.txt parsed to zero elements");
      cache = elements;
      return elements;
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
}

/** Already-loaded catalogue, or null. For render paths that must not wait. */
export function peekElements(): Element[] | null {
  return cache;
}

/**
 * Display name for a stored key, or null for a key the catalogue does not
 * carry. check-elements.mjs pins keys contiguous from 1, so this is an
 * index lookup with a guard rather than a scan.
 */
export function elementName(elements: Element[], z: number): string | null {
  if (z === NOT_LISTED) return "Not listed";
  const e = elements[z - 1];
  return e && e.z === z ? e.name : null;
}

// ── search ─────────────────────────────────────────────────────────────

// Same folding as pokedex.ts. Accents matter less here than there, but the
// shared contract matters more than the per-domain need.
function fold(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

let foldedFor: Element[] | null = null;
let folded: string[] = [];
function foldedNames(elements: Element[]): string[] {
  if (foldedFor !== elements) {
    folded = elements.map((e) => fold(e.name));
    foldedFor = elements;
  }
  return folded;
}

/**
 * Search the catalogue. Prefix beats word-start beats interior, and atomic
 * number breaks ties — the light elements are the ones a partial query most
 * likely means. The display name carries the symbol ("Gold (Au)"), so "au"
 * finds Gold by the word-start rule with no symbol-specific code path.
 */
export function searchElements(elements: Element[], q: string, max = 40): Element[] {
  const needle = fold(q.trim());
  if (!needle) return elements.slice(0, max);
  const names = foldedNames(elements);
  const hits: { e: Element; rank: number }[] = [];
  for (let i = 0; i < elements.length; i++) {
    const idx = names[i].indexOf(needle);
    if (idx < 0) continue;
    const rank = idx === 0 ? 0 : /[ (]/.test(names[i][idx - 1]) ? 1 : 2;
    hits.push({ e: elements[i], rank });
  }
  hits.sort((a, b) => a.rank - b.rank || a.e.z - b.e.z);
  return hits.slice(0, max).map((h) => h.e);
}

// ── the picker's view of this catalogue ────────────────────────────────
//
// An ordinary default export: ui/PickSearch is the only consumer and it
// imports this file. It published itself onto globalThis until D137, back
// when the spec layer looked catalogues up by name — nothing did any more,
// and its siblings (places, pokedex) never published at all.

const ELEMENTS_CATALOG = {
  NOT_LISTED,
  load: loadElements,
  peek: peekElements,
  parse: parseElements,
  search: searchElements,
  nameOf: elementName,
  key: (e: Element) => String(e.z),
};

export default ELEMENTS_CATALOG;
