// The city catalogue — the data behind the profile's city picker (D9).
//
// WHY THIS EXISTS. Until now `city` and `country` were free-text inputs
// (80 chars each) whose values went straight into the breakdown pipeline as
// map keys. functions/src/pure.ts excludes `city` from BREAKDOWN_DIMS for
// exactly that reason — "every distinct spelling would mint a key forever" —
// but `country` slipped in, so "Norway", "norway" and "NO" have been three
// separate cohorts, each below the 5-person floor, each suppressed. The
// country breakdown has been publishing nothing at all.
//
// A fixed vocabulary fixes that: one bucket per place, spelled one way, and
// `city` becomes safe to add to BREAKDOWN_DIMS alongside it.
//
// HOW A CITY GETS CHOSEN. Either the user searches this catalogue, or they
// tap "Use my location" and ./locate.ts turns one coarse fix into a city
// via nearestPlace() below — on the device, discarding the coordinate. Both
// paths produce the same canonical key, and the manual one always works, so
// declining the permission costs nothing but a few taps.
//
// The coordinates in this file describe CITIES, not people. They are
// read-only reference data shipped with the app, which is what lets the
// nearest-city question be answered with no server, no reverse-geocoding
// service, and no network at all.
//
// The catalogue is a static asset (public/cities.txt, ~139 KB) generated by
// scripts/build-cities.mjs and validated by scripts/check-cities.mjs. It is
// fetched once, lazily, the first time someone opens the picker — never on
// a cold start, and never over the network on a native build, where it
// ships inside the app package.

// Region display names come from the platform rather than the catalogue:
// 245 country names would be another 4 KB and would need translating, and
// Intl.DisplayNames already has them in the user's own language.
let regionNames: Intl.DisplayNames | null | undefined;
function countryName(code: string): string {
  if (regionNames === undefined) {
    try {
      regionNames = new Intl.DisplayNames(undefined, { type: "region" });
    } catch {
      // Very old WebView. The ISO code is a poor label but an honest one.
      regionNames = null;
    }
  }
  try {
    return regionNames?.of(code) || code;
  } catch {
    // Intl throws on codes it considers structurally invalid rather than
    // returning undefined; the catalogue has a few (e.g. XK for Kosovo).
    return code;
  }
}

export type Place = {
  /** City name exactly as it appears in the catalogue. */
  name: string;
  /** ISO 3166-1 alpha-2. */
  country: string;
  /** Population in thousands — used only to order search results. */
  popK: number;
  /** Latitude of the place, 2dp. Reference data about the city, not the user. */
  lat: number;
  /** Longitude of the place, 2dp. */
  lon: number;
};

/**
 * The canonical anchor value for a place: `"Oslo, NO"`.
 *
 * This string IS the breakdown bucket key, so it must stay under
 * BREAKDOWN_MAX_LABEL (40) and must avoid the characters breakdownBucket()
 * rejects. Both are enforced at build time by check-cities.mjs rather than
 * here, because a value that fails is not a runtime error to handle — it is
 * a catalogue that should never have shipped.
 */
export function placeKey(p: Place): string {
  return `${p.name}, ${p.country}`;
}

/** How a place reads in the UI: `"Oslo · Norway"`. */
export function placeLabel(p: Place): string {
  return `${p.name} · ${countryName(p.country)}`;
}

/**
 * Parse a stored anchor back into a place, or null if it is not one.
 *
 * Profiles written before the picker existed hold free text ("oslo",
 * "Oslo, Norway"). Those are not errors and must not be discarded — they
 * are simply not resolvable to a catalogue entry, so the picker shows the
 * raw text and asks for a re-pick rather than silently blanking someone's
 * profile.
 */
export function parsePlaceKey(key: string): Place | null {
  const m = /^(.+), ([A-Z]{2})$/.exec(key.trim());
  if (!m) return null;
  // popK/lat/lon are unknown here — a stored key carries a name and a
  // country and nothing else. Zeroed rather than optional so the shape is
  // one type everywhere; nothing that consumes a parsed key needs them
  // (labels and cohort lookups are name+country), and nearestPlace only
  // ever sees rows that came from the catalogue.
  return { name: m[1], country: m[2], popK: 0, lat: 0, lon: 0 };
}

/** The country code of a stored anchor, for the `country` breakdown dim. */
export function countryOf(key: string): string {
  return parsePlaceKey(key)?.country || "";
}

// ── loading ────────────────────────────────────────────────────────────

let cache: Place[] | null = null;
let inflight: Promise<Place[]> | null = null;

export function parseCatalogue(text: string): Place[] {
  const out: Place[] = [];
  let country = "";
  for (const line of text.split("\n")) {
    if (!line || line.charCodeAt(0) === 35 /* # */) continue;
    const tab = line.indexOf("\t");
    if (tab < 0) {
      // A bare line opens a country block. Anything that is not a plain
      // 2-letter code means the file is not what we think it is; stop
      // rather than attributing the rest of the world to a garbage code.
      if (!/^[A-Z]{2}$/.test(line)) break;
      country = line;
      continue;
    }
    if (!country) continue;
    const [name, popS, latS, lonS] = line.split("\t");
    // A row missing its coordinates would resolve to (0,0) and become the
    // nearest city for anyone in the Gulf of Guinea — and, worse, a
    // plausible answer for nobody in particular. Skip it instead.
    // check-cities.mjs makes sure this never fires on the shipped file.
    const lat = Number(latS);
    const lon = Number(lonS);
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) continue;
    out.push({ name, country, popK: Number(popS) || 0, lat, lon });
  }
  return out;
}

/**
 * Load the catalogue. Concurrent callers share one fetch; a failed load is
 * not cached, so opening the picker again retries.
 */
export function loadPlaces(): Promise<Place[]> {
  if (cache) return Promise.resolve(cache);
  if (inflight) return inflight;
  // BASE_URL, not a bare "/cities.txt": the Capacitor shells serve the
  // bundle from a local origin whose root is not always "/", and a web
  // deploy under a subpath would 404 on the absolute form.
  const url = `${import.meta.env.BASE_URL || "/"}cities.txt`.replace(/\/{2,}/g, "/");
  inflight = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`cities.txt: HTTP ${r.status}`);
      return r.text();
    })
    .then((text) => {
      const places = parseCatalogue(text);
      // An empty parse means the fetch succeeded against something that is
      // not the catalogue — a SPA index.html fallback, most likely. Treat
      // it as a failure so the picker says so instead of showing no results
      // for every query.
      if (!places.length) throw new Error("cities.txt parsed to zero places");
      cache = places;
      return places;
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
}

/** Already-loaded catalogue, or null. For render paths that must not wait. */
export function peekPlaces(): Place[] | null {
  return cache;
}

// ── search ─────────────────────────────────────────────────────────────

// Strip diacritics so "Malmo" finds "Malmö" and "san jose" finds "San José".
// Someone typing their own city on a phone keyboard should not have to
// produce the right accent to be found.
function fold(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

let foldedFor: Place[] | null = null;
let folded: string[] = [];
function foldedNames(places: Place[]): string[] {
  if (foldedFor !== places) {
    folded = places.map((p) => fold(p.name));
    foldedFor = places;
  }
  return folded;
}

/**
 * Search the catalogue. Prefix matches rank above interior matches, and
 * population breaks ties — so "york" offers New York before York, and
 * "san" offers San Antonio before Santa Rosa.
 *
 * `hint` is a country code that ranks first in the BLANK state only
 * (regionHint below is where it comes from). A typed query ignores it
 * entirely: typing is the user answering the question themselves.
 */
export function searchPlaces(places: Place[], q: string, max = 40, hint = ""): Place[] {
  const needle = fold(q.trim());
  if (!needle) {
    // No query: the hint country's cities first — Oslo and Bergen on a
    // phone whose clock says Europe/Oslo — then the largest cities in the
    // world, which was always a more useful blank state than the
    // alphabetically-first ones in Andorra, and now starts at home.
    return [...places]
      .sort((a, b) =>
        Number(b.country === hint) - Number(a.country === hint) || b.popK - a.popK)
      .slice(0, max);
  }
  const names = foldedNames(places);
  const hits: { p: Place; rank: number }[] = [];
  for (let i = 0; i < places.length; i++) {
    const idx = names[i].indexOf(needle);
    if (idx < 0) continue;
    // 0 = starts with the query, 1 = starts a later word, 2 = anywhere.
    const rank = idx === 0 ? 0 : names[i][idx - 1] === " " ? 1 : 2;
    hits.push({ p: places[i], rank });
  }
  hits.sort((a, b) => a.rank - b.rank || b.p.popK - a.p.popK);
  return hits.slice(0, max).map((h) => h.p);
}

// ── the blank-state region hint (D90) ──────────────────────────────────

/**
 * The catalogue country a clock zone names, or "".
 *
 * "Europe/Oslo" names Oslo; when the catalogue knows that city, its country
 * is the hint. Pure — the zone arrives as an argument, so no ordering test
 * can inherit the machine it runs on (places.test.ts asserts blank-state
 * order on a fixture that contains Oslo; an internal Intl read here would
 * make that assertion flip with the developer's wall clock).
 */
export function zoneCountry(places: Place[], zone: string): string {
  // The city is the last path segment, underscores as spaces — which also
  // reads three-segment zones ("America/Argentina/Buenos_Aires"). Folded
  // like the search, so "America/Sao_Paulo" still finds São Paulo.
  const city = fold((zone.split("/").pop() || "").replace(/_/g, " "));
  if (!city) return "";
  const names = foldedNames(places);
  // Two ranks, because IANA shortens: "America/New_York" names New York
  // City, "Asia/Kuwait" Kuwait City. 0 = the name itself; 1 = the name
  // continues after a word break — the break is required so "london" stays
  // out of "londonderry". Exact wins over prefix, and within a rank the
  // most populous namesake wins (Dublin IE over Dublin US): a zone is
  // named after its region's principal city.
  let best: Place | null = null;
  let bestRank = 2;
  for (let i = 0; i < places.length; i++) {
    const n = names[i];
    const rank = n === city ? 0
      : n.startsWith(city) && n.charCodeAt(city.length) === 32 ? 1
      : 2;
    if (rank === 2) continue;
    if (rank < bestRank || (rank === bestRank && (!best || places[i].popK > best.popK))) {
      best = places[i];
      bestRank = rank;
    }
  }
  return best ? best.country : "";
}

/**
 * zoneCountry for the clock THIS device is set to (D90).
 *
 * A hint, not a location: the IANA zone id is a setting the app already
 * renders every date with — no permission prompt, no sensor, no network,
 * no IP lookup — and it produces a sort order for the picker's blank
 * state, then is dropped. Never stored, never sent, never written to the
 * profile; the anchor is still only ever the city the user taps. The
 * NEAREST city stays behind the located tap (D9): a clock can say
 * "Norway", it cannot say where you are. A zone the catalogue cannot name
 * at all ("Etc/UTC", the tiny county zones) returns "" and the blank
 * state stays the world's: a hint may miss, it must not guess.
 */
export function regionHint(places: Place[]): string {
  try {
    return zoneCountry(places, Intl.DateTimeFormat().resolvedOptions().timeZone || "");
  } catch {
    // The same very-old-WebView guard countryName() carries.
    return "";
  }
}

// ── nearest city ───────────────────────────────────────────────────────

// Mean Earth radius, km. Only used for the distance we SHOW; the ranking
// itself never needs a unit.
const EARTH_KM = 6371;
const RAD = Math.PI / 180;

/**
 * The catalogue place closest to a coordinate, or null if the catalogue is
 * empty.
 *
 * THE WHOLE POINT: this runs on the device. A latitude and longitude go in,
 * a city name comes out, and the coordinate is discarded — it is never sent
 * to a server, never written to Firestore, never persisted. What leaves the
 * phone is "Oslo, NO", exactly the string the manual picker produces. The
 * app therefore learns which of ~11k cities someone is nearest and
 * nothing more precise, by construction rather than by promise.
 *
 * Ranks on the haversine central angle rather than a projected plane: a
 * flat-earth approximation is fine at mid-latitudes and wrong near the
 * poles and across the antimeridian, both of which are real places with
 * real cities (Longyearbyen, Anadyr, Nuku'alofa).
 */
export function nearestPlace(
  places: Place[],
  lat: number,
  lon: number,
): { place: Place; km: number } | null {
  if (!places.length || !Number.isFinite(lat) || !Number.isFinite(lon)) return null;
  const φ1 = lat * RAD;
  const sinφ1 = Math.sin(φ1);
  const cosφ1 = Math.cos(φ1);
  let best: Place | null = null;
  // Compare on cos(central angle): monotonically DEcreasing in distance, so
  // the largest cosine is the nearest place. Avoids an acos and a sqrt per
  // candidate across all of them.
  let bestCos = -Infinity;
  for (const p of places) {
    const φ2 = p.lat * RAD;
    const cosD =
      sinφ1 * Math.sin(φ2) + cosφ1 * Math.cos(φ2) * Math.cos((p.lon - lon) * RAD);
    if (cosD > bestCos) {
      bestCos = cosD;
      best = p;
    }
  }
  if (!best) return null;
  // Clamp before acos: accumulated float error can push an exact hit a hair
  // past 1, and acos(1.0000000000000002) is NaN.
  const km = EARTH_KM * Math.acos(Math.min(1, Math.max(-1, bestCos)));
  return { place: best, km };
}

// Published for the spec layer, which resolves cross-module references by
// name at render time (see src/v2/README.md). The shared scanner
// (scripts/spec-globals.mjs) recognises `globalThis.X =` and `window.X =`
// alike; a cast would be invisible to it, so neither form uses one.
//
// `globalThis` rather than live.ts's `window`, for one reason: everything
// above this line is pure and worth unit-testing, and `window` does not
// exist in the unit runner. live.ts pays for that with a stubGlobal dance
// in vote.test.ts; there is no reason to repeat it for a parser.
const PLACES = {
  load: loadPlaces,
  peek: peekPlaces,
  search: searchPlaces,
  regionHint,
  nearest: nearestPlace,
  key: placeKey,
  label: placeLabel,
  parse: parsePlaceKey,
  countryOf,
  countryName,
};

// No publication since D352's sweep: feed-read.js, its last window reader,
// imports the default export like every typed consumer always has.
export default PLACES;
