// The city catalogue — the data behind the profile's city picker (D9).
//
// WHY THIS EXISTS. Until now `city` and `country` were free-text inputs
// (80 chars each) whose values went straight into the breakdown pipeline as
// map keys. functions/src/pure.ts excludes `city` from BREAKDOWN_DIMS for
// exactly that reason — "every distinct spelling would mint a key forever" —
// but `country` slipped in, so "Norway", "norway" and "NO" have been three
// separate cohorts, each below the 5-person floor, each suppressed. The
// country breakdown has been publishing nothing at all.
//
// A fixed vocabulary fixes that: one bucket per place, spelled one way, and
// `city` becomes safe to add to BREAKDOWN_DIMS alongside it.
//
// WHY NO DEVICE LOCATION. The privacy panel says "No device location, ever
// — no GPS, no IP lookup", and both store listings declare Location: None.
// Picking from a list keeps every one of those claims true. It also happens
// to be more accurate than coarse GPS for the thing we actually want, which
// is the city a person considers theirs rather than the one they are
// standing in. See D9 for the alternatives that were priced and rejected.
//
// The catalogue is a static asset (public/cities.txt, ~139 KB) generated by
// scripts/build-cities.mjs and validated by scripts/check-cities.mjs. It is
// fetched once, lazily, the first time someone opens the picker — never on
// a cold start, and never over the network on a native build, where it
// ships inside the app package.

// Region display names come from the platform rather than the catalogue:
// 245 country names would be another 4 KB and would need translating, and
// Intl.DisplayNames already has them in the user's own language.
let regionNames: Intl.DisplayNames | null | undefined;
function countryName(code: string): string {
  if (regionNames === undefined) {
    try {
      regionNames = new Intl.DisplayNames(undefined, { type: "region" });
    } catch {
      // Very old WebView. The ISO code is a poor label but an honest one.
      regionNames = null;
    }
  }
  try {
    return regionNames?.of(code) || code;
  } catch {
    // Intl throws on codes it considers structurally invalid rather than
    // returning undefined; the catalogue has a few (e.g. XK for Kosovo).
    return code;
  }
}

export type Place = {
  /** City name exactly as it appears in the catalogue. */
  name: string;
  /** ISO 3166-1 alpha-2. */
  country: string;
  /** Population in thousands — used only to order search results. */
  popK: number;
};

/**
 * The canonical anchor value for a place: `"Oslo, NO"`.
 *
 * This string IS the breakdown bucket key, so it must stay under
 * BREAKDOWN_MAX_LABEL (40) and must avoid the characters breakdownBucket()
 * rejects. Both are enforced at build time by check-cities.mjs rather than
 * here, because a value that fails is not a runtime error to handle — it is
 * a catalogue that should never have shipped.
 */
export function placeKey(p: Place): string {
  return `${p.name}, ${p.country}`;
}

/** How a place reads in the UI: `"Oslo · Norway"`. */
export function placeLabel(p: Place): string {
  return `${p.name} · ${countryName(p.country)}`;
}

/**
 * Parse a stored anchor back into a place, or null if it is not one.
 *
 * Profiles written before the picker existed hold free text ("oslo",
 * "Oslo, Norway"). Those are not errors and must not be discarded — they
 * are simply not resolvable to a catalogue entry, so the picker shows the
 * raw text and asks for a re-pick rather than silently blanking someone's
 * profile.
 */
export function parsePlaceKey(key: string): Place | null {
  const m = /^(.+), ([A-Z]{2})$/.exec(key.trim());
  if (!m) return null;
  return { name: m[1], country: m[2], popK: 0 };
}

/** The country code of a stored anchor, for the `country` breakdown dim. */
export function countryOf(key: string): string {
  return parsePlaceKey(key)?.country || "";
}

// ── loading ────────────────────────────────────────────────────────────

let cache: Place[] | null = null;
let inflight: Promise<Place[]> | null = null;

export function parseCatalogue(text: string): Place[] {
  const out: Place[] = [];
  let country = "";
  for (const line of text.split("\n")) {
    if (!line || line.charCodeAt(0) === 35 /* # */) continue;
    const tab = line.indexOf("\t");
    if (tab < 0) {
      // A bare line opens a country block. Anything that is not a plain
      // 2-letter code means the file is not what we think it is; stop
      // rather than attributing the rest of the world to a garbage code.
      if (!/^[A-Z]{2}$/.test(line)) break;
      country = line;
      continue;
    }
    if (!country) continue;
    const popK = Number(line.slice(tab + 1));
    out.push({ name: line.slice(0, tab), country, popK: popK || 0 });
  }
  return out;
}

/**
 * Load the catalogue. Concurrent callers share one fetch; a failed load is
 * not cached, so opening the picker again retries.
 */
export function loadPlaces(): Promise<Place[]> {
  if (cache) return Promise.resolve(cache);
  if (inflight) return inflight;
  // BASE_URL, not a bare "/cities.txt": the Capacitor shells serve the
  // bundle from a local origin whose root is not always "/", and a web
  // deploy under a subpath would 404 on the absolute form.
  const url = `${import.meta.env.BASE_URL || "/"}cities.txt`.replace(/\/{2,}/g, "/");
  inflight = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`cities.txt: HTTP ${r.status}`);
      return r.text();
    })
    .then((text) => {
      const places = parseCatalogue(text);
      // An empty parse means the fetch succeeded against something that is
      // not the catalogue — a SPA index.html fallback, most likely. Treat
      // it as a failure so the picker says so instead of showing no results
      // for every query.
      if (!places.length) throw new Error("cities.txt parsed to zero places");
      cache = places;
      return places;
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
}

/** Already-loaded catalogue, or null. For render paths that must not wait. */
export function peekPlaces(): Place[] | null {
  return cache;
}

// ── search ─────────────────────────────────────────────────────────────

// Strip diacritics so "Malmo" finds "Malmö" and "san jose" finds "San José".
// Someone typing their own city on a phone keyboard should not have to
// produce the right accent to be found.
function fold(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

let foldedFor: Place[] | null = null;
let folded: string[] = [];
function foldedNames(places: Place[]): string[] {
  if (foldedFor !== places) {
    folded = places.map((p) => fold(p.name));
    foldedFor = places;
  }
  return folded;
}

/**
 * Search the catalogue. Prefix matches rank above interior matches, and
 * population breaks ties — so "york" offers New York before York, and
 * "san" offers San Antonio before Santa Rosa.
 */
export function searchPlaces(places: Place[], q: string, max = 40): Place[] {
  const needle = fold(q.trim());
  if (!needle) {
    // No query: the largest cities in the world, which is a more useful
    // blank state than the alphabetically-first ones in Andorra.
    return [...places].sort((a, b) => b.popK - a.popK).slice(0, max);
  }
  const names = foldedNames(places);
  const hits: { p: Place; rank: number }[] = [];
  for (let i = 0; i < places.length; i++) {
    const idx = names[i].indexOf(needle);
    if (idx < 0) continue;
    // 0 = starts with the query, 1 = starts a later word, 2 = anywhere.
    const rank = idx === 0 ? 0 : names[i][idx - 1] === " " ? 1 : 2;
    hits.push({ p: places[i], rank });
  }
  hits.sort((a, b) => a.rank - b.rank || b.p.popK - a.p.popK);
  return hits.slice(0, max).map((h) => h.p);
}

// Published for the spec layer, which resolves cross-module references by
// name at render time (see src/v2/README.md). The shared scanner
// (scripts/spec-globals.mjs) recognises `globalThis.X =` and `window.X =`
// alike; a cast would be invisible to it, so neither form uses one.
//
// `globalThis` rather than live.ts's `window`, for one reason: everything
// above this line is pure and worth unit-testing, and `window` does not
// exist in the unit runner. live.ts pays for that with a stubGlobal dance
// in vote.test.ts; there is no reason to repeat it for a parser.
const PLACES = {
  load: loadPlaces,
  peek: peekPlaces,
  search: searchPlaces,
  key: placeKey,
  label: placeLabel,
  parse: parsePlaceKey,
  countryOf,
  countryName,
};

declare global {
  interface Window {
    PLACES?: typeof PLACES;
  }
}

// Object.assign rather than `globalThis.PLACES = PLACES`: the latter needs
// an index signature on typeof globalThis that a `declare global` interface
// on Window does not provide (TS7017). Same form the ui/ panels use, and
// the scanner matches it.
Object.assign(globalThis, { PLACES });

export default PLACES;
