// pokedex.ts — the Pokédex catalogue behind the feed's `pick` card
// (docs/CATALOG-QUESTIONS.md: a favourite is one pick from a shipped
// catalogue, and the stored answer is the entry's KEY, never a string).
//
// The places.ts contract, one level simpler: the asset is public/pokedex.txt
// (`dex<TAB>name`, generated by scripts/build-pokedex.mjs, drift-gated by
// scripts/check-pokedex.mjs), the key is the National Dex number, and the
// display name is resolved from the key at render time — the
// PLACES.countryName pattern: store the key, display the name.

export interface Species {
  /** National Dex number — the stored answer key. */
  dex: number;
  name: string;
}

// "Not listed" answers store this instead of a dex number. It is a real
// bucket in the reveal (published as a count, never enumerated) and 0 is
// unused by the catalogue, so the whole answer domain stays one integer.
export const NOT_LISTED = 0;

// ── loading ────────────────────────────────────────────────────────────

let cache: Species[] | null = null;
let inflight: Promise<Species[]> | null = null;

export function parsePokedex(text: string): Species[] {
  const out: Species[] = [];
  for (const line of text.split("\n")) {
    if (!line || line.charCodeAt(0) === 35 /* # */) continue;
    const tab = line.indexOf("\t");
    if (tab < 1) continue;
    const dex = Number(line.slice(0, tab));
    const name = line.slice(tab + 1);
    // A non-integer key or an empty name is a file this parser does not
    // know. check-pokedex.mjs makes sure this never fires on the shipped
    // file — being lenient here would mean resolving answers against a
    // half-understood catalogue.
    if (!Number.isInteger(dex) || dex < 1 || !name) continue;
    out.push({ dex, name });
  }
  return out;
}

/**
 * Load the catalogue. Concurrent callers share one fetch; a failed load is
 * not cached, so opening the picker again retries.
 */
export function loadPokedex(): Promise<Species[]> {
  if (cache) return Promise.resolve(cache);
  if (inflight) return inflight;
  // BASE_URL, not a bare "/pokedex.txt" — the places.ts argument: Capacitor
  // shells and subpath deploys do not serve the bundle from "/".
  const url = `${import.meta.env.BASE_URL || "/"}pokedex.txt`.replace(/\/{2,}/g, "/");
  inflight = fetch(url)
    .then((r) => {
      if (!r.ok) throw new Error(`pokedex.txt: HTTP ${r.status}`);
      return r.text();
    })
    .then((text) => {
      const species = parsePokedex(text);
      // Zero entries means the fetch succeeded against something that is
      // not the catalogue — a SPA index.html fallback, most likely.
      if (!species.length) throw new Error("pokedex.txt parsed to zero species");
      cache = species;
      return species;
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
}

/** Already-loaded catalogue, or null. For render paths that must not wait. */
export function peekPokedex(): Species[] | null {
  return cache;
}

/**
 * Display name for a stored key, or null for a key the catalogue does not
 * carry. check-pokedex.mjs pins keys contiguous from 1, so this is an index
 * lookup with a guard rather than a scan.
 */
export function speciesName(species: Species[], dex: number): string | null {
  if (dex === NOT_LISTED) return "Not listed";
  const s = species[dex - 1];
  return s && s.dex === dex ? s.name : null;
}

// ── search ─────────────────────────────────────────────────────────────

// Same folding as places.ts: "flabebe" has to find Flabébé without the
// phone keyboard producing an é.
function fold(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

let foldedFor: Species[] | null = null;
let folded: string[] = [];
function foldedNames(species: Species[]): string[] {
  if (foldedFor !== species) {
    folded = species.map((s) => fold(s.name));
    foldedFor = species;
  }
  return folded;
}

/**
 * Search the catalogue. Prefix beats word-start beats interior, and dex
 * order breaks ties — the earliest generations are the ones a partial query
 * most likely means. No query returns the catalogue's own order.
 */
export function searchPokedex(species: Species[], q: string, max = 40): Species[] {
  const needle = fold(q.trim());
  if (!needle) return species.slice(0, max);
  const names = foldedNames(species);
  const hits: { s: Species; rank: number }[] = [];
  for (let i = 0; i < species.length; i++) {
    const idx = names[i].indexOf(needle);
    if (idx < 0) continue;
    const rank = idx === 0 ? 0 : names[i][idx - 1] === " " ? 1 : 2;
    hits.push({ s: species[i], rank });
  }
  hits.sort((a, b) => a.rank - b.rank || a.s.dex - b.s.dex);
  return hits.slice(0, max).map((h) => h.s);
}

// ── the spec-layer bridge ──────────────────────────────────────────────

const POKEDEX = {
  NOT_LISTED,
  load: loadPokedex,
  peek: peekPokedex,
  parse: parsePokedex,
  search: searchPokedex,
  nameOf: speciesName,
  key: (s: Species) => String(s.dex),
};

declare global {
  interface Window {
    POKEDEX?: typeof POKEDEX;
  }
}

// Object.assign rather than `globalThis.POKEDEX = …` — the places.ts
// argument (TS7017), and the form the scanner matches.
Object.assign(globalThis, { POKEDEX });

export default POKEDEX;
