#!/usr/bin/env node
// asc-push.mjs — push design/store/listing.json to App Store Connect.
//
//   node scripts/asc-push.mjs                 # report the diff, change nothing
//   node scripts/asc-push.mjs --apply         # write it
//   node scripts/asc-push.mjs --age-rating    # the IARC answers
//   node scripts/asc-push.mjs --privacy       # the nutrition label, as a form to type in
//   node scripts/asc-push.mjs --screenshots   # what image sets exist
//   node scripts/asc-push.mjs --all           # text + age rating + privacy
//
// Every mode is dry-run without --apply.
//
// WHY THIS EXISTS. listing.json is already the reviewed copy, already held
// against both stores' character limits by check-store-listing.mjs, and
// already the single source for the screenshot captions. Retyping it into
// a web form is an hour that also introduces the one failure that file was
// created to prevent: the store saying something the repo does not.
//
// SCOPE. It WRITES three things: the listing text, the age rating and —
// with --screenshots --apply — the screenshot sets. It REPORTS one more:
// the privacy nutrition label, which it cannot write because Apple's API
// has no App Privacy resource at all. That is a constraint rather than a
// scope decision, and establishing it cost three rounds of 4xx; the
// --privacy block below says how it was finally settled. Pricing and
// availability are untouched.
//
// THE ATTESTATIONS, AND A REVERSAL. This file used to refuse the privacy
// questionnaire and the age rating on the grounds that "a script that
// fills in an attestation is a script that answers a legal question on
// your behalf". That reasoning confused two different things: DECIDING an
// answer and TRANSCRIBING one. The decision lives in
// design/store/app-privacy.json — committed, reviewable in a diff, with
// the why on every row, and held equal to docs/STORE-FORMS.md by
// check:store-forms. The owner approves that file. This script types it in
// where Apple lets it (the age rating) and prints it where Apple does not
// (the privacy label) — the argument is the same either way, and the
// difference between the two is only which one has an endpoint.
//
// Typing it in by hand was never the safeguard it looked like. It is ~40
// clicks that have to agree with docs/data-inventory.md, with nothing
// checking that they do, re-done from memory every time a row changes —
// which is exactly how the "collects no email or name via Google" claim
// survived in three documents at once. A diff is a better review surface
// than a web form.
//
// What still is not automated, and deliberately: submitting for review.
// That one is irreversible and outward-facing, and it should cost a
// deliberate human click.
//
// Dry run by default. --apply is required to write anything.
//
// Auth: the same App Store Connect API key the release workflow uses
// (docs/IOS-RELEASE.md). Either export them:
//   ASC_KEY_ID, ASC_ISSUER_ID, ASC_PRIVATE_KEY   (the .p8 contents)
// or pass --key-file path/to/AuthKey_XXXX.p8 with the two ids as env vars.
//
// Node stdlib only: the JWT is ES256, which node:crypto signs directly as
// long as the signature is asked for in the JOSE format rather than DER —
// see sign() below, which is the one non-obvious line in this file.

import { readFileSync, existsSync, readdirSync } from "node:fs";
import { createSign, createHash } from "node:crypto";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argv = process.argv.slice(2);
const argOf = (f) => { const i = argv.indexOf(f); return i >= 0 ? argv[i + 1] : null; };
const APPLY = argv.includes("--apply");
const SCREENSHOTS = argv.includes("--screenshots");
const ALL = argv.includes("--all");
const AGE_RATING = ALL || argv.includes("--age-rating");
const PRIVACY = ALL || argv.includes("--privacy");
// Text is the default so a bare `asc:push` keeps behaving as it always
// has. Asking for only --age-rating should not also silently rewrite the
// description, so text turns itself off once a specific mode is named.
const TEXT = ALL || !(AGE_RATING || PRIVACY);
const LOCALE = argOf("--locale") || "en-US";

// Screenshot upload knobs. PROFILE names a directory under
// design/store/screenshots/ — the same ids gen-screenshots writes.
const PROFILE = argOf("--profile") || "iphone-6.9";
// --screenshots-dir names the base holding <profile>/*.png and manifest.json.
// It exists because the captures are GITIGNORED (.gitignore: they are build
// output, regenerated by the workflow) — so a test that read the real
// directory would pass on a machine that had run the harness and fail in CI,
// which is exactly what it did. The tests now build a fixture and point here.
const SHOTS_BASE = argOf("--screenshots-dir") || join(root, "design/store/screenshots");
// Apple's ScreenshotDisplayType. A flag rather than a constant because the
// enum gains members when new hardware ships, and because a wrong value
// fails LOUDLY — the API answers with the list of valid ones. That is the
// property that makes this safe to automate at all.
const DISPLAY_TYPE = argOf("--display-type") || "APP_IPHONE_67";
const ALLOW_DEMO = argv.includes("--allow-demo");

// The editable version is the one not yet released. Anything in a live or
// in-review state must not be edited by a script running unattended.
// Declared here rather than beside its other use because the screenshot
// path needs it too, and a const referenced above its declaration is a
// temporal-dead-zone crash rather than a warning.
const EDITABLE = new Set([
  "PREPARE_FOR_SUBMISSION", "DEVELOPER_REJECTED", "REJECTED",
  "METADATA_REJECTED", "INVALID_BINARY",
]);

// --privacy-file so the attestation's source is nameable rather than
// baked in: the tests point it at fixtures to exercise the guards, and a
// second store's answers would be a second file rather than a fork.
// Read ABOVE the credential gate because a privacy-only run never reaches
// Apple — see the early exit below.
const privacy = JSON.parse(readFileSync(
  resolve(argOf("--privacy-file") || join(root, "design/store/app-privacy.json")), "utf8",
));

const KEY_ID = process.env.ASC_KEY_ID;
const ISSUER_ID = process.env.ASC_ISSUER_ID;
const KEY_FILE = argOf("--key-file");
const PRIVATE_KEY = KEY_FILE
  ? readFileSync(resolve(KEY_FILE), "utf8")
  : process.env.ASC_PRIVATE_KEY;

// Every other section talks to Apple; the privacy label does not, because
// there is no App Privacy resource in the API to talk to (D73) — it is a
// printout. Demanding a signing key for it is how the one launch step that
// needs no account becomes a step nobody can run, which is the failure
// SHIP-CHECKLIST §1 records twice for the seed: an instruction survived
// review because running it needed something nobody had.
const NEEDS_APPLE = TEXT || AGE_RATING || SCREENSHOTS;

if (PRIVACY && !NEEDS_APPLE) {
  printPrivacyForm();
  // Same vocabulary as the tail, and deliberately NOT its "already matches
  // the repo" clause: this run never asked Apple anything, so claiming
  // agreement with it would be the one kind of sentence this file exists
  // to keep out of a launch step.
  console.log(`\nasc-push: nothing to write — this run never contacted App Store Connect. Still yours: ${stillYours()}.`);
  process.exit(0);
}

if (!KEY_ID || !ISSUER_ID || !PRIVATE_KEY) {
  console.error(
    "asc-push: needs ASC_KEY_ID, ASC_ISSUER_ID and the private key.\n"
    + "    export ASC_KEY_ID=... ASC_ISSUER_ID=... ASC_PRIVATE_KEY=\"$(cat AuthKey_XXXX.p8)\"\n"
    + "    or pass --key-file path/to/AuthKey_XXXX.p8\n"
    + "    docs/IOS-RELEASE.md § 1 says where the key comes from.",
  );
  process.exit(1);
}

const listing = JSON.parse(readFileSync(join(root, "design/store/listing.json"), "utf8"));
const BUNDLE_ID = listing.shared.bundleId;

// ── auth ────────────────────────────────────────────────────────────
const b64u = (buf) => Buffer.from(buf).toString("base64url");

function token() {
  const header = { alg: "ES256", kid: KEY_ID, typ: "JWT" };
  const now = Math.floor(Date.now() / 1000);
  // Apple rejects anything longer than 20 minutes. 10 is plenty and
  // leaves room for a slow upload without re-minting mid-request.
  const payload = { iss: ISSUER_ID, iat: now, exp: now + 600, aud: "appstoreconnect-v1" };
  const signingInput = `${b64u(JSON.stringify(header))}.${b64u(JSON.stringify(payload))}`;
  // dsaEncoding: "ieee-p1363" is the whole trick. Node's default for EC is
  // DER, which JWT verifiers reject with a signature error that reads like
  // a wrong key — the single most confusing way to get ASC auth wrong.
  const sig = createSign("SHA256")
    .update(signingInput)
    .sign({ key: PRIVATE_KEY, dsaEncoding: "ieee-p1363" });
  return `${signingInput}.${b64u(sig)}`;
}

// ASC_API_BASE exists so this file can be exercised against a stub. It has
// no account to run against in review and no way to be tried safely against
// a real one — the first live run would be against the owner's listing —
// so the alternative to a seam here is shipping the request shapes
// unverified. Unset in every real use.
const API = process.env.ASC_API_BASE || "https://api.appstoreconnect.apple.com";

async function call(method, path, body) {
  const res = await fetch(path.startsWith("http") ? path : `${API}${path}`, {
    method,
    headers: {
      authorization: `Bearer ${token()}`,
      ...(body ? { "content-type": "application/json" } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  if (!res.ok) {
    let detail = text;
    try {
      detail = JSON.parse(text).errors?.map((e) => `${e.title}: ${e.detail}`).join("\n    ") || text;
    } catch { /* non-JSON error body — show it raw */ }
    throw new Error(`${method} ${path} → ${res.status}\n    ${detail}`);
  }
  return text ? JSON.parse(text) : null;
}

// ── locate the app and the editable version ─────────────────────────
const apps = await call("GET", `/v1/apps?filter[bundleId]=${encodeURIComponent(BUNDLE_ID)}`);
const app = apps.data?.[0];
if (!app) {
  console.error(
    `asc-push: no app with bundle id ${BUNDLE_ID} in this account.\n`
    + "    The App Store Connect app record has to exist first — this script\n"
    + "    fills a record in, it does not create one.",
  );
  process.exit(1);
}
console.log(`asc-push: ${app.attributes.name} (${BUNDLE_ID})${APPLY ? "" : "   [DRY RUN]"}`);

if (SCREENSHOTS) {
  // This was read-only until 2026-08-07, on the reasoning that the
  // display-type enum "should not be guessed at from a machine with no
  // account to test against". The account now exists, so the objection is
  // gone — and the guess is avoidable anyway: --display-type is a flag, and
  // a wrong one is a 4xx from Apple naming the valid values, not a silent
  // wrong upload. That is a better failure than ten minutes of dragging.
  const versions = await call("GET", `/v1/apps/${app.id}/appStoreVersions?limit=10`);
  const version = versions.data?.find((v) => EDITABLE.has(v.attributes.appStoreState));
  if (!version) {
    console.error(
      "asc-push: no editable App Store version to attach screenshots to.\n"
      + `    States found: ${(versions.data || []).map((v) => v.attributes.appStoreState).join(", ") || "none"}`,
    );
    process.exit(1);
  }
  const locs = await call("GET", `/v1/appStoreVersions/${version.id}/appStoreVersionLocalizations`);
  const loc = locs.data.find((l) => l.attributes.locale === LOCALE);
  if (!loc) {
    console.error(`asc-push: no ${LOCALE} localization. Add it in App Store Connect, or pass --locale.`);
    process.exit(1);
  }

  const dir = join(SHOTS_BASE, PROFILE);
  if (!existsSync(dir)) {
    console.error(`asc-push: no captures at design/store/screenshots/${PROFILE}/ — run npm run build:screenshots.`);
    process.exit(1);
  }
  const files = readdirSync(dir).filter((f) => f.endsWith(".png")).sort();

  // THE 2.3.3 GATE, and the reason this refuses rather than warns.
  // gen-screenshots records per-capture `demoOnlyAffordances`: controls
  // gated on !S.live — the demo's Comments and "Who voted what" sheets,
  // which are populated from sample-data.js.
  //
  // Still a 2.3.3 problem after D98, for a narrowed reason. Named
  // who-voted IS a shipped feature now, so the gate is no longer "this
  // advertises a feature that does not exist" — it is "this advertises
  // real people who do not exist" (D1, the half D98 kept). The live
  // who-voted panel has its own accessible name and captures cleanly. It is also the most expensive kind of
  // mistake here: it costs a full review cycle, days after the upload.
  const manifestPath = join(SHOTS_BASE, "manifest.json");
  const manifest = existsSync(manifestPath)
    ? JSON.parse(readFileSync(manifestPath, "utf8"))
    : null;
  const shotMeta = new Map(
    (manifest?.profiles?.[PROFILE]?.shots || []).map((s) => [s.file, s]),
  );
  const unsafe = files.filter((f) => (shotMeta.get(f)?.demoOnlyAffordances || []).length);
  if (unsafe.length && !ALLOW_DEMO) {
    console.error(
      `asc-push: ${unsafe.length} capture(s) show demo-only UI and will not be uploaded:\n`
      + unsafe.map((f) => `      ${f} — ${shotMeta.get(f).demoOnlyAffordances.join(", ")}`).join("\n")
      + "\n    Those sheets are populated from sample-data.js, so the people in"
      + "\n    them do not exist and App Store 2.3.3 wants screenshots that"
      + "\n    reflect the app. Recapture in live mode — since D98 a live"
      + "\n    capture shows real named voters, which is the shot you want"
      + "\n    anyway — or pass --allow-demo if you have decided otherwise,"
      + "\n    which is a decision worth writing down rather than a flag to reach for.",
    );
    process.exit(1);
  }
  if (manifest && manifest.mode !== "live") {
    console.log(`  note: these captures were taken in ${String(manifest.mode).toUpperCase()} mode.`);
  }

  // Find or create the set for this display type. Sets are per
  // (localization, displayType); Apple rejects an unknown type by NAMING the
  // valid ones, which is why guessing is survivable here and silent
  // mis-sizing is not — gen-screenshots already asserts pixel dimensions.
  const sets = await call("GET", `/v1/appStoreVersionLocalizations/${loc.id}/appScreenshotSets`);
  let set = sets.data.find((s) => s.attributes.screenshotDisplayType === DISPLAY_TYPE);
  console.log(
    `  ${loc.attributes.locale} / ${DISPLAY_TYPE}: `
    + `${set ? "existing set" : "no set yet"}, ${files.length} local capture(s)`,
  );

  const existingNames = new Set();
  if (set) {
    const have = await call("GET", `/v1/appScreenshotSets/${set.id}/appScreenshots`);
    for (const s of have.data) {
      if (s.attributes.assetDeliveryState?.state === "COMPLETE") {
        existingNames.add(s.attributes.fileName);
      }
    }
  }
  const todo = files.filter((f) => !existingNames.has(f));
  if (!todo.length) {
    console.log(`  = screenshots: all ${files.length} already uploaded.`);
  } else {
    // `+` only. This used to tick all of them here, before a single byte
    // moved — so a run that died on the third of six left four false ✓ in
    // the log. The per-file confirmation is at the end of the loop below,
    // after the commit PATCH returns (D74).
    for (const f of todo) console.log(`  + upload ${f}`);
    if (!APPLY) {
      console.log(`\nasc-push: ${todo.length} screenshot(s) would upload. Re-run with --apply.`);
      process.exit(0);
    }

    if (!set) {
      set = (await call("POST", "/v1/appScreenshotSets", {
        data: {
          type: "appScreenshotSets",
          attributes: { screenshotDisplayType: DISPLAY_TYPE },
          relationships: {
            appStoreVersionLocalization: {
              data: { type: "appStoreVersionLocalizations", id: loc.id },
            },
          },
        },
      })).data;
    }

    for (const f of todo) {
      const bytes = readFileSync(join(dir, f));
      // 1 — reserve. Apple answers with the exact PUTs to make.
      const reserved = (await call("POST", "/v1/appScreenshots", {
        data: {
          type: "appScreenshots",
          attributes: { fileSize: bytes.length, fileName: f },
          relationships: { appScreenshotSet: { data: { type: "appScreenshotSets", id: set.id } } },
        },
      })).data;
      // 2 — send the bytes exactly as instructed. offset/length are Apple's,
      // not ours: a large asset comes back as several operations, and
      // assuming one whole-file PUT is how this breaks on a bigger image.
      for (const op of reserved.attributes.uploadOperations || []) {
        const slice = bytes.subarray(op.offset, op.offset + op.length);
        const headers = Object.fromEntries((op.requestHeaders || []).map((h) => [h.name, h.value]));
        const put = await fetch(op.url, { method: op.method || "PUT", headers, body: slice });
        if (!put.ok) {
          console.error(`asc-push: upload of ${f} failed at ${op.url} → ${put.status}`);
          process.exit(1);
        }
      }
      // 3 — commit, with the checksum Apple verifies the bytes against. MD5
      // here is Apple's choice of integrity check, not a security decision.
      await call("PATCH", `/v1/appScreenshots/${reserved.id}`, {
        data: {
          type: "appScreenshots",
          id: reserved.id,
          attributes: { uploaded: true, sourceFileChecksum: createHash("md5").update(bytes).digest("hex") },
        },
      });
      console.log(`  ✓ uploaded ${f} (${(bytes.length / 1024).toFixed(0)} KiB)`);
    }
    console.log(`\nasc-push: ${todo.length} screenshot(s) uploaded.`);
  }
  process.exit(0);
}

// EDITABLE is declared near the top of this file — the screenshot path
// needs it before this point, and a const used above its declaration is a
// temporal-dead-zone crash rather than a warning.
//
// NO include=ageRatingDeclaration here. It was written that way, on the
// assumption that the declaration hangs off the version, and Apple answered:
//
//   GET /v1/apps/…/appStoreVersions?…&include=ageRatingDeclaration → 400
//   A parameter has an invalid value: 'ageRatingDeclaration' is not a valid
//   relationship name
//
// It belongs to the APP INFO, not the version — the same split the text
// fields follow, and for the same reason: an age rating survives versions.
// Fetched with the appInfo below.
const versions = await call("GET", `/v1/apps/${app.id}/appStoreVersions?limit=10`);
const version = versions.data?.find((v) => EDITABLE.has(v.attributes.appStoreState));
if (!version) {
  console.error(
    "asc-push: no editable App Store version.\n"
    + `    States found: ${versions.data.map((v) => v.attributes.appStoreState).join(", ") || "none"}\n`
    + "    Create a new version in App Store Connect first. This script will not\n"
    + "    edit one that is live or in review.",
  );
  process.exit(1);
}

// ── the two places the text lives ───────────────────────────────────
// Apple splits it: name/subtitle/privacy URL belong to the APP (they
// survive versions), while description/keywords/what's-new belong to the
// VERSION. Sending a field to the wrong one is a 409 that reads like a
// permissions problem.
// include=ageRatingDeclaration is valid HERE, which is the correction the
// 400 above bought. One round trip serves both the localizations and the
// age rating.
const infos = await call("GET", `/v1/apps/${app.id}/appInfos?include=ageRatingDeclaration`);
const info = infos.data[0];
const infoLocs = await call("GET", `/v1/appInfos/${info.id}/appInfoLocalizations`);
const infoLoc = infoLocs.data.find((l) => l.attributes.locale === LOCALE);

const verLocs = await call("GET", `/v1/appStoreVersions/${version.id}/appStoreVersionLocalizations`);
const verLoc = verLocs.data.find((l) => l.attributes.locale === LOCALE);

// Only the text push needs a localization. Gating this on TEXT matters:
// --age-rating and --privacy are app-level and locale-free, and failing
// them on a missing en-US localization would be a wrong answer to a
// question they never asked.
if (TEXT && (!infoLoc || !verLoc)) {
  console.error(`asc-push: no ${LOCALE} localization. Add it in App Store Connect, or pass --locale.`);
  process.exit(1);
}

const a = listing.apple;
const s = listing.shared;

const plan = [
  { id: infoLoc.id, kind: "appInfoLocalizations", label: "app info", fields: {
    name: a.name,
    subtitle: a.subtitle,
    privacyPolicyUrl: s.privacyPolicyUrl,
  } },
  { id: verLoc.id, kind: "appStoreVersionLocalizations", label: "version", fields: {
    description: a.description,
    keywords: a.keywords,
    promotionalText: a.promotionalText,
    supportUrl: s.supportUrl,
    marketingUrl: s.supportUrl,
  } },
  // whatsNew IS a version localization field and belongs in the group
  // above. It gets its own PATCH because Apple refuses it on a FIRST
  // release — "What's New in This Version" has no meaning when there is no
  // previous version — with a 409 naming the attribute. A PATCH is atomic,
  // so one rejected field took the other five down with it: the run that
  // taught this printed ✓ against description, keywords, promotionalText,
  // supportUrl and marketingUrl, and wrote none of them.
  //
  // Split rather than state-modelled. The alternative was deciding up front
  // whether the app has ever had a released version, which means encoding
  // Apple's version state machine from the outside and guessing which of
  // READY_FOR_SALE / PENDING_DEVELOPER_RELEASE / REPLACED_WITH_NEW_VERSION
  // count. Apple already answers that question exactly; D73 is the whole
  // argument for asking rather than guessing.
  {
    id: verLoc.id,
    kind: "appStoreVersionLocalizations",
    label: "version",
    fields: { whatsNew: a.whatsNew },
    // Only this 409, only this field. Any other failure still throws.
    skipOn409:
      "Apple refuses `whatsNew` on a first release — there is no previous\n"
      + "      version for it to be new against. It will apply on the first UPDATE,\n"
      + "      and listing.json already holds the text. Nothing to do.",
  },
];

let changes = 0;
if (TEXT) {
  for (const group of plan) {
    const current = group.kind === "appInfoLocalizations" ? infoLoc.attributes : verLoc.attributes;
    const diff = {};
    for (const [k, v] of Object.entries(group.fields)) {
      if ((current[k] ?? "") !== v) diff[k] = v;
    }
    const keys = Object.keys(diff);
    if (!keys.length) { console.log(`  = ${group.label}: already matches listing.json`); continue; }

    const short = (t) => (t.length > 60 ? `${t.slice(0, 57)}…` : t).replace(/\n/g, "⏎");
    const report = (mark) => {
      for (const k of keys) {
        console.log(`  ${mark} ${group.label}.${k}: "${short(current[k] ?? "")}" → "${short(diff[k])}"`);
      }
    };

    if (!APPLY) { changes += keys.length; report("+"); continue; }

    // REPORT AFTER THE WRITE, never before. This printed ✓ first and
    // PATCHed second, so a rejected field produced eight ticks and five
    // unwritten fields — a summary describing an outcome the run did not
    // have, which is the same failure the seed workflow and this repo's job
    // summaries each shipped once. `+` before the write is fine; it is a
    // statement of intent. `✓` is a statement of fact and has to be earned.
    try {
      await call("PATCH", `/v1/${group.kind}/${group.id}`, {
        data: { type: group.kind, id: group.id, attributes: diff },
      });
    } catch (err) {
      if (group.skipOn409 && /→ 409\b/.test(err.message) && /cannot be edited/i.test(err.message)) {
        console.log(`  — ${group.label}.${keys.join(", ")}: skipped. ${group.skipOn409}`);
        continue;
      }
      throw err;
    }
    changes += keys.length;
    report("✓");
  }
}

// ── the age rating ──────────────────────────────────────────────────
// One PATCH against the version's own ageRatingDeclaration. The
// declaration always exists — Apple creates it with the version — so this
// is an update and never a create, and the id has to be read rather than
// guessed.
//
// The `$`-prefixed keys in app-privacy.json are commentary for whoever
// reviews the file, not fields. Filtering them here rather than stripping
// them from the file keeps the reasoning next to the value it explains,
// which is the whole reason that file is readable at all.
if (AGE_RATING) {
  // From the APP INFO, not the version — see the 400 quoted at the versions
  // fetch above. Apple creates the declaration with the app, so its absence
  // means this fetch did not carry relationships, never that the rating is
  // unset; the message says so rather than sending someone to the console.
  const decl = info.relationships?.ageRatingDeclaration?.data;
  if (!decl) {
    console.error(
      "asc-push: this app info carries no ageRatingDeclaration relationship.\n"
      + "    Apple creates one with the app, so this means the appInfos fetch\n"
      + "    dropped the include — not that the rating is unset. Check the\n"
      + "    ?include=ageRatingDeclaration on the appInfos call.",
    );
    process.exit(1);
  }
  const want = Object.fromEntries(
    Object.entries(privacy.ageRating).filter(([k]) => !k.startsWith("$")),
  );

  // The current values come from the appInfos `included` array, NOT from a
  // GET on the declaration. Apple refuses that outright:
  //
  //   GET /v1/ageRatingDeclarations/{id} → 403
  //   The resource 'ageRatingDeclarations' does not allow 'GET_INSTANCE'.
  //   Allowed operation is: UPDATE
  //
  // Write-only, which is unusual enough to be worth stating. The include
  // added for the id turns out to carry the attributes too, so the diff
  // costs nothing — the same request answers both questions.
  const included = (infos.included || []).find(
    (r) => r.type === "ageRatingDeclarations" && r.id === decl.id,
  );
  const current = included?.attributes || null;

  // No attributes means no diff is possible, and the honest response is to
  // send everything rather than to guess or to skip. PATCH is idempotent
  // here — every key is a fixed enum or boolean from a reviewed file — so
  // an unnecessary write costs a request and changes nothing.
  const diff = {};
  for (const [k, v] of Object.entries(want)) {
    if (!current || current[k] !== v) diff[k] = v;
  }
  if (!current) {
    console.log(
      "  note: the declaration's current values did not arrive with the app info,\n"
      + "        so this sends all of them rather than only what differs.",
    );
  }
  const keys = Object.keys(diff);
  if (!keys.length) {
    console.log("  = age rating: already matches app-privacy.json");
  } else {
    const report = (mark) => {
      for (const k of keys) {
        console.log(`  ${mark} ageRating.${k}: ${JSON.stringify(current?.[k])} → ${JSON.stringify(diff[k])}`);
      }
    };
    if (!APPLY) {
      changes += keys.length;
      report("+");
    } else {
      // AFTER the PATCH, never before — D74, and this is the site that
      // proved fixing it in one place was not fixing it. The text block was
      // corrected while this one still ticked fourteen fields above a 409
      // listing eight missing required attributes, none of which were
      // written. One instance of a mistake is rarely the only one; grep the
      // shape, do not patch the report.
      await call("PATCH", `/v1/ageRatingDeclarations/${decl.id}`, {
        data: { type: "ageRatingDeclarations", id: decl.id, attributes: diff },
      });
      changes += keys.length;
      report("✓");
    }
  }
}

// ── the privacy nutrition label ─────────────────────────────────────
// A REPORT, NOT A PUSH — and that is Apple's constraint, not a scope
// decision taken here. The App Store Connect API has no App Privacy
// resource of any kind. Verified three independent ways, because one
// error message is not evidence about what an API contains:
//
//   1. The live API. GET /v1/apps/{id}/appDataUsages answers 404, "The
//      relationship 'appDataUsages' does not exist".
//   2. Apple's own OpenAPI spec (4.2, 925 paths). The string "DataUsage"
//      does not occur in it anywhere, and the `App` schema's relationship
//      list — 43 entries, down to `webhooks` and
//      `androidToIosAppMappingDetails` — has nothing privacy-shaped.
//   3. The documentation index. App Store › App Metadata lists app infos,
//      localizations, versions, screenshots, previews, categories and age
//      ratings. There is no privacy section, and the release notes through
//      4.4 never mention one.
//
// This block used to POST and DELETE `appDataUsages` rows against an
// add-missing / delete-extra reconciliation. It never worked and could not
// have. Three versions of it failed in production with a 400, then a 403,
// then that 404 — and each time the answer LOOKED like a wrong path, so
// the next attempt was a different path rather than the question "does
// this resource exist at all?". Asking that question directly took ten
// minutes and ended it. The rule worth keeping: when an API answers three
// different 4xx to three different guesses, stop guessing paths and go
// read what resources it has.
//
// What is left is worth having. Every answer is already decided, reviewed
// and gated — app-privacy.json holds it with the reasoning on each row,
// check:store-forms holds it equal to docs/STORE-FORMS.md. Printing it in
// the order the web form asks turns ~40 clicks-from-memory into
// transcription, which is the same argument this file's header makes for
// the fields it CAN write.
if (PRIVACY) printPrivacyForm();

// A function so the privacy-only run can print it above the credential
// gate. Declared here, where the section it prints has always lived.
function printPrivacyForm() {
  // Apple's form labels, derived from the enum rather than tabulated. A
  // hand-kept id→label map is one more figure to go stale, and the ids are
  // unambiguous on their own; the entire cost of deriving is that
  // "USER_ID" reads "User Id".
  const label = (s) => String(s).toLowerCase().split("_")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(" ");

  console.log("\n  App Privacy — App Store Connect › App Privacy › Edit");
  console.log("  The API cannot write this. Below is the form, in the order it asks.");
  console.log(`\n  Tracking: ${privacy.tracking.used === false ? "No" : "YES"}`);
  if (privacy.tracking.used !== false) {
    // The rows below carry no per-row tracking answer, because this file
    // models tracking as uniformly off. If that ever changes, the form
    // asks a question this report does not answer — and printing the rows
    // without saying so would be exactly the silent under-declaration
    // app-privacy.json warns about.
    console.log(
      "    ⚠ app-privacy.json no longer says tracking is off. The form then asks a\n"
      + "      tracking question PER ROW, which this report does not answer. Take\n"
      + "      those answers from docs/STORE-FORMS.md, not from the list below.",
    );
  }

  console.log(`\n  Collected — ${privacy.collected.length} data types:`);
  for (const row of privacy.collected) {
    console.log(`    • ${label(row.category)} › ${label(row.type)}`);
    console.log(`        purposes:           ${row.purposes.map(label).join(", ")}`);
    console.log(`        linked to identity: ${row.linked ? "Yes" : "No"}`);
    console.log(`        used for tracking:  ${privacy.tracking.used === false ? "No" : "see the warning above"}`);
  }

  // Only the absences app-privacy.json names individually. The ~22 in
  // `others` are ones nobody is tempted to tick, and printing them would
  // bury the three that are genuinely arguable.
  const tempting = Object.entries(privacy.notCollected)
    .filter(([k, v]) => !k.startsWith("$") && k !== "others" && typeof v === "string");
  if (tempting.length) {
    console.log("\n  Leave UNTICKED — these look tickable and are not:");
    for (const [k, why] of tempting) {
      console.log(`    • ${label(k)}`);
      // Whole reason, wrapped — not the first sentence. Truncating there was
      // tried and lost the point on one of the three: EMAILS_OR_TEXT_MESSAGES
      // opens "No, AT LAUNCH." and the sentence that matters ("takes are
      // circle-scoped and have no live surface") is the second one.
      let line = "       ";
      for (const word of why.split(/\s+/)) {
        if (line.length + word.length + 1 > 78) { console.log(line); line = "       "; }
        line += ` ${word}`;
      }
      console.log(line);
    }
  }

  console.log(
    "\n  Read docs/STORE-FORMS.md before ticking anything: what you are entering is a\n"
    + "  legal statement about what the app collects.",
  );
}

// A function so the privacy-only early exit above can say the same thing.
function stillYours() {
  return [
    PRIVACY && "the privacy label above — hand-entered, because Apple's API has no endpoint for it",
    !SCREENSHOTS && "screenshots (--screenshots to see what is there)",
    "submitting for review — deliberately manual, it is the irreversible one",
  ].filter(Boolean).join("; ");
}

const still = stillYours();

console.log(
  // `changes` counts what this script can WRITE. "Nothing to do" would be a
  // lie whenever --privacy has just printed a form that still has to be
  // typed in, so every branch names what is still outstanding.
  !changes
    ? `\nasc-push: nothing to write — App Store Connect already matches the repo. Still yours: ${still}.`
    : APPLY
      ? `\nasc-push: ${changes} change(s) applied. Still yours: ${still}.`
      : `\nasc-push: ${changes} change(s) would be made. Re-run with --apply. Still yours: ${still}.`,
);
