// Generates public/colors.txt — the CSS named-colour catalogue behind the
// feed's `pick` cards (docs/QUESTION-FARM.md § creating new catalogues;
// the domain machinery is docs/CATALOG-QUESTIONS.md / D14–D17).
//
// Source rules apply verbatim: `css-color-names` is a devDependency used
// once, here (the `pokemon`/`world-countries` pattern) — the CSS
// specification's named colours, MIT, name → hex. Never hand-written
// entries; a wrong key silently resolves someone's stored favourite to
// the wrong colour forever.
//
// KEYS ARE THE COLOUR ITSELF, PLUS ONE: 1 + parseInt(hex, 16) — an
// external stable id in rule 2's best sense, because a named colour's
// identity IS its hex. The +1 is uniform and load-bearing: key 0 is the
// pick system's Not-listed bucket everywhere (CROWD, canon, the fold),
// and black is #000000 — without the offset the spec's most-picked dark
// colour would file itself under "Not listed". No minting, no ordering
// dependence; a regeneration cannot renumber.
// The one wrinkle the spec hands us is ALIASES — nine hexes carry two
// names each (aqua/cyan, fuchsia/magenta, and the gray/grey spelling
// pairs) — and two names on one key would be two rows claiming one
// stored answer. The dedup rule is deterministic, not curatorial: the
// alphabetically-first name per hex wins, so `aqua` stands for cyan and
// `gray` for grey. Documented here and pinned by check-catalogs.
//
// The COMMITTED FILE is still the registry of record: on regeneration
// this builder reads public/colors.txt first and preserves every
// existing key→name row verbatim (a name the source later dropped or
// renamed STAYS — deleting it would orphan stored answers); only
// genuinely new hexes append. CSS never removes named colours, so this
// clause should never fire — it exists so that if it ever would, the
// drift gate sees the disagreement instead of the bank absorbing it.
import { createRequire } from "node:module";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { regenerateCatalogKeys } from "./catalog-keys-lib.mjs";

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "colors.txt");

let map;
try {
  map = require("css-color-names");
} catch {
  console.error(
    "build-colors: `css-color-names` is not installed.\n" +
      "It is a devDependency used only by this script:\n" +
      "  npm i --no-save css-color-names@1.0.1",
  );
  process.exit(1);
}

// hex → alphabetically-first name (the deterministic alias rule above)
const byKey = new Map();
for (const name of Object.keys(map).sort()) {
  const hex = String(map[name]).toLowerCase();
  if (!/^#[0-9a-f]{6}$/.test(hex)) {
    console.error(`build-colors: unexpected hex ${hex} for ${name}`);
    process.exit(1);
  }
  const key = 1 + parseInt(hex.slice(1), 16);
  if (!byKey.has(key)) byKey.set(key, name);
}

// committed file is the registry of record — existing rows survive verbatim
const existing = new Map();
if (existsSync(OUT)) {
  for (const line of readFileSync(OUT, "utf8").split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const [k, name] = line.split("\t");
    existing.set(Number(k), name);
  }
}
for (const [k, name] of existing) byKey.set(k, name);

const rows = [...byKey.entries()].sort((a, b) => a[0] - b[0]);
const header =
  `# InSight colours catalogue — GENERATED by scripts/build-colors.mjs, do not edit.\n` +
  `# Source: the CSS specification's named colours via the \`css-color-names\`\n` +
  `# npm package (MIT). Keys are the colour itself plus one — 1 +\n` +
  `# parseInt(hex, 16); the offset keeps black off the Not-listed key 0 —\n` +
  `# so they are externally stable and regeneration cannot renumber. Nine\n` +
  `# hexes carry two names (aqua/cyan, fuchsia/magenta, gray/grey pairs);\n` +
  `# the alphabetically-first name per hex wins, deterministically. The\n` +
  `# committed file is the registry of record: existing rows survive any\n` +
  `# regeneration verbatim, new hexes only append.\n` +
  `# ${rows.length} entries.\n`;
const body = rows.map(([k, name]) => `${k}\t${name}`).join("\n") + "\n";
writeFileSync(OUT, header + body);
const gz = gzipSync(Buffer.from(header + body)).length;
console.log(
  `build-colors: wrote ${rows.length} colours to public/colors.txt ` +
    `(${(header + body).length} bytes, ~${(gz / 1024).toFixed(1)} KiB gzipped)`,
);

regenerateCatalogKeys(root, "build-colors");
