// Generates public/dogs.txt — the dog-breed catalogue behind the feed's
// `pick` cards (docs/QUESTION-FARM.md § creating new catalogues; the
// domain machinery is docs/CATALOG-QUESTIONS.md / D14–D17).
//
// Source rules apply verbatim: `dog-breeds` is a devDependency used once,
// here (the `pokemon`/`world-countries` pattern) — 554 breeds, MIT,
// Wikipedia-derived names. Never hand-written entries; a wrong key
// silently resolves someone's stored answer to the wrong dog forever.
//
// WHY MINTED KEYS, AND WHAT HOLDS THEM: unlike dex numbers, ISO codes or
// codepoints, dog breeds have no numeric standard this source carries —
// so keys are catalogue-minted under the manual's append-only discipline.
// The COMMITTED FILE is the registry of record, not the package: on
// regeneration this builder reads public/dogs.txt first, preserves every
// existing key→name pair verbatim (an entry whose breed later vanishes
// from the source STAYS — deleting it would orphan stored answers), and
// only appends genuinely new names with the next free keys. The initial
// mint is 1..N in alphabetical order; nothing after it may renumber.
import { createRequire } from "node:module";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { regenerateCatalogKeys } from "./catalog-keys-lib.mjs";

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "dogs.txt");

let data;
try {
  data = require("dog-breeds").all;
} catch {
  console.error(
    "build-dogs: `dog-breeds` is not installed.\n" +
      "It is a devDependency used only by this script:\n" +
      "  npm i --no-save dog-breeds@2.1.0",
  );
  process.exit(1);
}

// Names from the source, format-checked. Display is the name alone —
// origins are sometimes multi-part ("Scotland, United Kingdom") and a
// countries catalogue already exists; a dog picker searches dog names.
const sourceNames = [];
const seen = new Set();
for (const b of data) {
  const name = (b?.name || "").trim();
  if (!name) {
    console.error("build-dogs: entry with an empty name");
    process.exit(1);
  }
  if (/[\t\n\r]/.test(name) || name.startsWith("#")) {
    console.error(`build-dogs: name would corrupt the format: ${JSON.stringify(name)}`);
    process.exit(1);
  }
  const nk = name.toLowerCase();
  if (seen.has(nk)) {
    console.error(`build-dogs: duplicate name ${JSON.stringify(name)} — search could not resolve it`);
    process.exit(1);
  }
  seen.add(nk);
  sourceNames.push(name);
}
if (sourceNames.length < 400) {
  console.error(`build-dogs: only ${sourceNames.length} rows — refusing to write a stub catalogue`);
  process.exit(1);
}

// ── the append-only mint ────────────────────────────────────────────────
// Existing pairs from the committed file are the registry of record.
const existing = []; // [key, name] in file order
const existingByName = new Map();
let maxKey = 0;
if (existsSync(OUT)) {
  for (const line of readFileSync(OUT, "utf8").split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const tab = line.indexOf("\t");
    if (tab < 1) continue;
    const key = Number(line.slice(0, tab));
    const name = line.slice(tab + 1);
    existing.push({ key, name });
    existingByName.set(name.toLowerCase(), key);
    if (key > maxKey) maxKey = key;
  }
}

const rows = [...existing];
const fresh = sourceNames
  .filter((n) => !existingByName.has(n.toLowerCase()))
  .sort((a, b) => a.localeCompare(b, "en"));
for (const name of fresh) rows.push({ key: ++maxKey, name });
// First generation: `existing` is empty, so every name is fresh and the
// mint comes out 1..N alphabetical.
const dropped = existing.length
  ? sourceNames.length + existing.length - rows.length
  : 0;

const lines = [
  "# InSight dog-breed catalogue — GENERATED by scripts/build-dogs.mjs, do not edit.",
  "# Source: the `dog-breeds` npm package (MIT; Wikipedia-derived names).",
  "# Keys are CATALOGUE-MINTED and append-only: this committed file is the",
  "# registry of record — regeneration preserves every existing key→name",
  "# pair verbatim and only appends new breeds with the next free keys.",
  "# An entry never renumbers and never leaves; stored answers depend on it.",
  `# ${rows.length} entries, initial mint alphabetical. Format: \`key<TAB>name\`.`,
];
for (const r of rows) lines.push(`${r.key}\t${r.name}`);
const text = lines.join("\n") + "\n";
writeFileSync(OUT, text);
console.log(
  `build-dogs: wrote ${rows.length} breeds (${existing.length} preserved, ` +
    `${rows.length - existing.length} appended${dropped ? `, source lost ${dropped} — kept anyway` : ""}) — ` +
    `${(text.length / 1024).toFixed(1)} KB raw, ${(gzipSync(text).length / 1024).toFixed(1)} KB gzipped`,
);

regenerateCatalogKeys(root, "build-dogs");
