// Generates public/emoji.txt — the emoji catalogue behind the feed's
// `pick` cards (docs/QUESTION-FARM.md § creating new catalogues; the
// domain machinery is docs/CATALOG-QUESTIONS.md / D14–D17).
//
// THE FIRST DOMAIN BUILT UNDER THE NEW-CATALOGUE CONTRACT, so the source
// rules apply verbatim: `unicode-emoji-json` is a devDependency used once,
// here (the `pokemon`/`all-the-cities` pattern) — Unicode.org emoji data as
// JSON, MIT-packaged, CLDR names. Never hand-written entries; a wrong key
// silently resolves someone's stored favourite to the wrong thing forever.
//
// WHY CODEPOINT KEYS: the stored answer is an integer key, and Unicode's
// stability policy means a codepoint's meaning never changes — these are
// the most stable keys any domain can have, better even than dex numbers.
// Only single-codepoint emoji are included (after stripping the VS16
// variation selector): multi-codepoint sequences — flags, ZWJ combos like
// families and professions, skin-tone applications — cannot be one integer
// and fold to their base or to "Not listed", which the picker copy says.
//
// The display name embeds the character ("😂 face with tears of joy") so
// the picker shows real emoji without a renderer of its own; search folds
// over the whole string, so typing "joy" still finds it.
import { createRequire } from "node:module";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "emoji.txt");

let data;
try {
  data = require("unicode-emoji-json");
} catch {
  console.error(
    "build-emoji: `unicode-emoji-json` is not installed.\n" +
      "It is a devDependency used only by this script:\n" +
      "  npm i --no-save unicode-emoji-json@0.9.0",
  );
  process.exit(1);
}

const rows = [];
const seenKeys = new Set();
for (const [ch, info] of Object.entries(data)) {
  const cps = [...ch].map((c) => c.codePointAt(0)).filter((c) => c !== 0xfe0f);
  if (cps.length !== 1) continue; // sequences cannot be one integer key
  const key = cps[0];
  const name = `${ch} ${info.name}`.trim();
  // Format corruption is a hard failure, never a filter.
  if (/[\t\n\r]/.test(name) || name.startsWith("#")) {
    console.error(`build-emoji: name would corrupt the format: ${JSON.stringify(name)}`);
    process.exit(1);
  }
  if (seenKeys.has(key)) {
    console.error(`build-emoji: duplicate codepoint ${key} (${name})`);
    process.exit(1);
  }
  seenKeys.add(key);
  rows.push({ key, name });
}
if (rows.length < 1000) {
  console.error(`build-emoji: only ${rows.length} rows — refusing to write a stub catalogue`);
  process.exit(1);
}

const lines = [
  "# InSight emoji catalogue — GENERATED by scripts/build-emoji.mjs, do not edit.",
  "# Source: unicode.org emoji data via the `unicode-emoji-json` npm package",
  "# (MIT); names are CLDR short names. Keys are Unicode codepoints — stable",
  "# by Unicode policy, forever. Single-codepoint emoji only (VS16 stripped):",
  "# sequences (flags, ZWJ combos, applied skin tones) fold to their base or",
  "# to the Not-listed bucket.",
  `# ${rows.length} entries, CLDR order. Format: \`key<TAB>char name\`.`,
];
for (const r of rows) lines.push(`${r.key}\t${r.name}`);
const text = lines.join("\n") + "\n";
writeFileSync(OUT, text);
console.log(
  `build-emoji: wrote ${rows.length} emoji — ` +
    `${(text.length / 1024).toFixed(1)} KB raw, ${(gzipSync(text).length / 1024).toFixed(1)} KB gzipped`,
);

// ── regenerate the trigger's key sets from ALL committed catalogues ─────
// Shared derivation with scripts/build-catalog.mjs: whichever builder ran
// last, catalogKeys.ts equals exactly the committed files, and
// check-catalogs.mjs fails CI on any disagreement.
const parseKeys = (file) => {
  if (!existsSync(file)) return [];
  const keys = [];
  for (const line of readFileSync(file, "utf8").split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const tab = line.indexOf("\t");
    if (tab > 0) keys.push(Number(line.slice(0, tab)));
  }
  return keys;
};
const filmKeys = parseKeys(join(root, "public", "films.txt"));
const artistKeys = parseKeys(join(root, "public", "artists.txt"));
const emojiKeys = parseKeys(OUT);
const countryKeys = parseKeys(join(root, "public", "countries.txt"));
const setLiteral = (keys) =>
  keys.length ? `new Set<number>([\n  ${keys.join(", ")},\n])` : "new Set<number>()";
writeFileSync(
  join(root, "functions", "src", "catalogKeys.ts"),
  [
    "// GENERATED from the committed catalogues in public/ by",
    "// scripts/build-catalog.mjs, scripts/build-emoji.mjs and",
    "// scripts/build-countries.mjs (any regenerates all sets) — do not",
    "// hand-edit. scripts/check-catalogs.mjs re-derives these from the",
    "// committed files and fails CI on any disagreement, in ci.yml and",
    "// backend-checks.yml both.",
    "//",
    "// The trigger validates catalog `entity` keys against these sets",
    "// (functions/src/v2.ts, CATALOG_DOMAINS): an empty set means the",
    "// domain's catalogue has not been generated yet, so nothing",
    "// aggregates for it — fail-safe until an operator runs the builder",
    "// (D15 records why films/artists generation is an operator step).",
    `export const FILM_KEYS: ReadonlySet<number> = ${setLiteral(filmKeys)};`,
    `export const ARTIST_KEYS: ReadonlySet<number> = ${setLiteral(artistKeys)};`,
    `export const EMOJI_KEYS: ReadonlySet<number> = ${setLiteral(emojiKeys)};`,
    `export const COUNTRY_KEYS: ReadonlySet<number> = ${setLiteral(countryKeys)};`,
    "",
  ].join("\n"),
);
console.log(
  `build-emoji: regenerated functions/src/catalogKeys.ts ` +
    `(films ${filmKeys.length}, artists ${artistKeys.length}, emoji ${emojiKeys.length}, countries ${countryKeys.length})`,
);
