// Generates public/pokedex.txt — the offline catalogue behind the `pick`
// question type's picker (docs/CATALOG-QUESTIONS.md), pilot domain.
//
// WHY A GENERATED, COMMITTED ARTIFACT — the build-cities.mjs argument,
// smaller: the `pokemon` package is a devDependency used once, here, and
// never reaches a bundle. The output is committed so a clean checkout
// builds without it; `npm run check:pokedex` validates the committed file
// (format, not regeneration — same split as check-cities.mjs).
//
// WHY `dex<TAB>name` AND NOT BARE NAMES IN ORDER: the stored answer is the
// dex number — an answer is a catalogue key, never a string. If keys were
// implied by line position, one deleted line would silently renumber every
// species after it and old answers would resolve to the wrong name.
// Explicit keys turn that into a loud contiguity failure in the gate.
//
// Data: English display names in National Dex order from the `pokemon`
// package (MIT) — proper typography included (Nidoran♀, Farfetch'd,
// Type: Null, Flabébé). The names are Nintendo/Creatures/GAME FREAK
// trademarks used nominatively to ask about preferences; whether that
// posture is fine for a shipped "favourite" poll is an OPEN pre-ship
// check recorded in docs/CATALOG-QUESTIONS.md, not something this script
// settles.
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "public", "pokedex.txt");

let pokemon;
try {
  pokemon = require("pokemon");
} catch {
  console.error(
    "build-pokedex: `pokemon` is not installed.\n" +
      "It is a devDependency used only by this script:\n" +
      "  npm i --no-save pokemon@3.3.1",
  );
  process.exit(1);
}

const names = pokemon.all("en");

// A tab, newline or leading "#" would corrupt the format itself; a
// duplicate name would make the picker's search ambiguous. Nothing in the
// dataset does either today, so both are hard failures rather than
// filters — if they start happening the format or the source needs fixing,
// not the data hiding (the build-cities.mjs stance).
const malformed = names.filter(
  (n) => !n || /[\t\n\r]/.test(n) || n.startsWith("#") || n !== n.trim(),
);
if (malformed.length) {
  console.error(
    `build-pokedex: ${malformed.length} name(s) would corrupt the file format: ` +
      JSON.stringify(malformed.slice(0, 5)),
  );
  process.exit(1);
}
if (new Set(names).size !== names.length) {
  console.error("build-pokedex: duplicate names in the dataset");
  process.exit(1);
}

const lines = [
  "# InSight Pokédex catalogue — GENERATED by scripts/build-pokedex.mjs, do not edit.",
  "# Source: the `pokemon` npm package (MIT); English display names, National Dex order.",
  `# ${names.length} species. Format: \`dex<TAB>name\`; dex is contiguous from 1 and is`,
  "# the stored answer key (docs/CATALOG-QUESTIONS.md: a key, never a string).",
  "#",
  "# Names are Nintendo/Creatures/GAME FREAK trademarks, used nominatively.",
  "# Trademark posture for a shipped poll is an open pre-ship check — see",
  "# docs/CATALOG-QUESTIONS.md.",
];
names.forEach((name, i) => lines.push(`${i + 1}\t${name}`));
const text = lines.join("\n") + "\n";

writeFileSync(OUT, text);
console.log(
  `build-pokedex: wrote ${names.length} species — ` +
    `${(text.length / 1024).toFixed(1)} KB raw, ${(gzipSync(text).length / 1024).toFixed(1)} KB gzipped`,
);
