// Ported from design/spec-modules/duels-data.js (the historical prototype — no sync
// script survives; THIS file is the live source of the BEHAVIOR, hand-edits
// and all), and re-ported at D435 from design/standalone-2026-09-09/
// duels-data.js — the owner's "how 1v1s and Groups work now" — so the demo
// build plays what live plays: ROUNDS, not days.
//
// The group/1v1 banks themselves moved to content/duel-questions.json
// (2026-08-03, the D32 learn-data shape): one source feeds both this module
// and the seeded Firestore bank via scripts/gen-v2content.mjs, so the demo
// banks and the live docs cannot drift. (A static JSON import, not a
// cross-module import — the spec layer's no-imports convention bans
// load-order coupling between modules, which data has none of.)
// OFF THE GLOBAL BRIDGE (D108): `DUELS` is a named export, not a
// `window.DUELS`, so its consumers hold it as a module binding that load
// order cannot leave unset. Nothing here publishes to global scope.
// The DEMO SAMPLE, not the bank (D433 — D284's shape one bank over). This
// import used to be `duel-questions.json` whole, under `check:content`'s
// 24 KiB cap, and the daily burst (D426) was one run from crossing it. The
// sample is the first few served questions of each group kind and each
// 1v1 domain plus the packs those votes name, generated by
// `scripts/gen-duel-sample.mjs` and held equal to its source by
// `check:duel-sample`; a live build never loads this module at all — it
// reads the seeded bank through `data/deck.ts`'s duelQFor (pinned in
// test/daily-live-duels.test.jsx). Every read below is a slice of what
// the bank would give it, so the pool arithmetic is unchanged; only the
// pools are shorter.
import DUEL_CONTENT from '../../../content/duel-sample.json';
import { FRIENDS } from './follows.js';
import { IS_DATA } from './sample-data.js';
// The four seats, with their lines (D435) — the same list the live
// instrument reads, so the demo's "Here, you are the one who gets things
// going" is the live app's sentence. `castText` is the live deck's {name}
// substitution for a cast round. Both are pure typed modules.
import { SEATS } from '../data/roles';
import { castText } from '../data/deck';

// duels-data.js — the "know each other" layer, as ROUNDS (D426, D435).
//  · GROUP: a room plays a role vote three rounds in four and a rating on
//    the fourth (a phase per room staggers which). Everyone answers blind;
//    a round reveals WITH NAMES when everyone has played or at its 48-hour
//    deadline, and you may answer up to LEAD rounds ahead of the room.
//    Nothing in a group is predicted or called.
//  · 1v1: three own rounds, then a CAST — "Most days, Liv is…" — repeating.
//    You answer, then guess what they said (on a cast, what they said you
//    are); the round reveals the moment both are in.
// Partner behaviour is deterministic mock; your own answers, your custom
// groups and your invites persist to localStorage. The circle = your friends
// (FRIENDS). Read/being-read scores feed the Map's People branch and the
// person page's Together section.
//
// The binding is hoisted above the IIFE and assigned inside it — the shape
// DAILYQ, FRIENDS and SCENES took, and for the same reason: the wrapper is
// vestigial (an ESM module already has its own scope) but unwrapping it
// re-indents the file and would bury the one real edit in a whitespace
// diff. ESM exports are live and this module finishes evaluating before any
// importer's body runs, so consumers always see the object.
export let DUELS;
(function () {
  const LEAD = 5;
  const DEADLINE = 48 * 3600e3;
  const HOUR = 3600e3;
  function h01(s) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
    return ((h >>> 8) % 100000) / 100000;
  }

  // ── persistence — your answers + your social edits ─────────────────────────
  // v2: the round-keyed shapes. A v1 record (one answer a day, keyed by
  // question) is simply left behind under its own key; the purge sweeps
  // `insight.*` by prefix, so it goes with the rest.
  const LS = 'insight.duels.v2';
  // One shape for the cold load AND the purge listener below — a field
  // added here is automatically fresh in both, so they cannot diverge.
  function normalize(v) {
    const s = v && typeof v === 'object' ? v : {};
    s.epoch = s.epoch || Date.now();        // when this device's rounds began — the deadlines count from it
    s.duo = s.duo || {};                    // pid → { round → { a, g, qid } }
    s.duoTheirs = s.duoTheirs || {};        // pid → { round → ts } — the partner's (mock) answer landed
    s.duoDue = s.duoDue || {};              // pid → { round → ts } — when it will
    s.groups = s.groups || {};              // gid → { round → { a, late, qid } }
    s.groupIn = s.groupIn || {};            // gid → { round → { pid → ts } } — who has (mock) played
    s.groupDue = s.groupDue || {};          // gid → { round → { pid → ts } } — when they will
    s.duoList = Array.isArray(s.duoList) ? s.duoList : null; // active 1v1 pids (null = seed)
    s.duoInv = s.duoInv || {};              // pid → invite ts (waiting on them)
    s.myGroups = Array.isArray(s.myGroups) ? s.myGroups : []; // custom groups
    s.groupIds = s.groupIds || {};          // seeded-gid → edited member ids
    s.groupPend = s.groupPend || {};        // gid → { pid → invite ts }
    s.left = Array.isArray(s.left) ? s.left : []; // gids you left
    s.duoMode = s.duoMode || {};            // pid → 'friends' | 'romantic' (which pool this 1v1 draws from)
    return s;
  }
  let S;
  try { S = normalize(JSON.parse(localStorage.getItem(LS) || '{}')); } catch (e) { S = normalize({}); }
  const listeners = new Set();
  const fire = () => listeners.forEach((f) => { try { f(); } catch (e) { /* one listener throwing must not stop the others being notified. */ } });
  const save = () => { try { localStorage.setItem(LS, JSON.stringify(S)); } catch (e) { /* localStorage can throw: private mode, quota, disabled storage. Persistence here is best-effort and the in-memory state stays correct. */ } fire(); };
  // The purge (data/live.ts, D51): drop your duel answers, groups and 1v1
  // edits too, or the next answer's save() writes the previous account's
  // back under the new uid. fire() without save() — do not re-create the
  // purged key.
  window.addEventListener('insight:local-purge', () => { S = normalize({}); fire(); });

  // ── the circle — your friends ───────────────────────────────────────────────
  // Fallback if FRIENDS is absent, and the first-run 1v1 roster (duoList).
  // Eight rather than five so the daily's 1v1 rail, the Map's People branch
  // and impressions() all run at a size where they have to rank; the other
  // seeded friends stay unpaired on purpose — they are what duoAvailable()
  // offers. Every id here must be in follows.js SEED too, since duoIds()
  // filters the list through FRIENDS.isFriend and a non-friend would sit in
  // storage invisible.
  const IDS = ['f1', 'f2', 'f4', 'f6', 'f3', 'f12', 'f17', 'f14'];
  const allPeople = () => IS_DATA.people || [];
  const circleIds = () => FRIENDS.list();
  function members() { return circleIds().map((id) => allPeople().find((p) => p.id === id)).filter(Boolean); }
  const personOf = (pid) => allPeople().find((p) => p.id === pid);
  const first = (p) => ((p && p.name) || '').split(' ')[0];

  // ── the mock clock: invites accept, partners answer, rooms fill in ─────────
  // Deterministic short delays, swept every 2.5 s while anything is pending.
  function accDelay(k) { return 9000 + Math.floor(h01('acc' + k) * 18000); }
  function sweep() {
    const now = Date.now(); let hit = false;
    Object.keys(S.duoInv).forEach((pid) => {
      if (now - S.duoInv[pid] >= accDelay('d' + pid)) { delete S.duoInv[pid]; if (!duoList().includes(pid)) duoList().push(pid); hit = true; }
    });
    Object.keys(S.groupPend).forEach((gid) => {
      const m = S.groupPend[gid];
      Object.keys(m).forEach((pid) => { if (now - m[pid] >= accDelay('g' + gid + pid)) { delete m[pid]; hit = true; } });
    });
    Object.keys(S.duoDue).forEach((pid) => {
      Object.keys(S.duoDue[pid]).forEach((r) => {
        if (now >= S.duoDue[pid][r]) {
          delete S.duoDue[pid][r];
          S.duoTheirs[pid] = S.duoTheirs[pid] || {};
          S.duoTheirs[pid][r] = now;
          hit = true;
        }
      });
    });
    Object.keys(S.groupDue).forEach((gid) => {
      Object.keys(S.groupDue[gid]).forEach((r) => {
        const due = S.groupDue[gid][r];
        Object.keys(due).forEach((pid) => {
          if (now >= due[pid]) {
            delete due[pid];
            S.groupIn[gid] = S.groupIn[gid] || {};
            S.groupIn[gid][r] = S.groupIn[gid][r] || {};
            S.groupIn[gid][r][pid] = now;
            hit = true;
          }
        });
      });
    });
    if (hit) save();
  }
  const hasPend = () => Object.keys(S.duoInv).length > 0
    || Object.keys(S.groupPend).some((g) => Object.keys(S.groupPend[g]).length > 0)
    || Object.keys(S.duoDue).some((p) => Object.keys(S.duoDue[p]).length > 0)
    || Object.keys(S.groupDue).some((g) => Object.keys(S.groupDue[g]).some((r) => Object.keys(S.groupDue[g][r]).length > 0));
  let timer = null;
  function ensureTimer() {
    if (timer) return;
    timer = setInterval(() => { if (!hasPend()) { clearInterval(timer); timer = null; return; } sweep(); }, 2500);
  }
  if (hasPend()) ensureTimer();

  // ── THE BANK: the D433 sample of content/duel-questions.json ───────────────
  // The group as a CAST (D432/D435): a role vote is a `pick` naming its
  // scenario pack (the packs are written once in `scenarios`) and the ROLE
  // it casts, with the role's SEAT; a `rate` question carries two poles and
  // the five step labels are derived the way the seed derives them. The
  // older group kinds in the file (`us`, `classic`, a pick with no role)
  // are not played here: a room plays role votes and ratings, nothing else
  // (the owner's 2026-09-09 brief — VISION-2026-09-09 §3.7 has the open row
  // about the older questions). The sample keeps bank order, so the packs
  // rotate the way the seed serves them.
  const PACKS = new Map((DUEL_CONTENT.scenarios || []).map((s) => [s.id, s]));
  const stepLabels = (poles) => [poles[0], 'mostly ' + poles[0], 'in between', 'mostly ' + poles[1], poles[1]];
  const stepLabel = (poles, i) => stepLabels(poles)[i];
  const ALL_ROLES = DUEL_CONTENT.group
    .filter((q) => q.active !== false && q.kind === 'pick' && q.role && q.scen && PACKS.has(q.scen))
    .map((q) => ({ key: q.id, id: q.role.id, seat: q.role.seat, label: q.role.label, prompt: q.prompt, scen: PACKS.get(q.scen) }));
  const RATE_QS = DUEL_CONTENT.group
    .filter((q) => q.active !== false && q.kind === 'rate' && Array.isArray(q.poles) && q.poles.length === 2)
    .map((q) => ({ id: q.id, dim: q.dim || q.id, prompt: q.prompt, poles: q.poles }));
  const SCENARIOS = [...PACKS.values()].map((sc) => ({ ...sc, roles: ALL_ROLES.filter((r) => r.scen.id === sc.id) }));
  const seatOf = (id) => SEATS.find((s) => s.id === id) || null;

  // ── seeded groups — each runs the shared pool at its own offset ────────────
  // Four sizes on purpose (7 · 4 · 2 · 5): a group's map, its seats and its
  // ratings all read differently at two members than at seven, and a role
  // vote's ballot is the members (activeMembers + You), so the largest
  // group is also the widest face grid the daily has to lay out. Three
  // STATES on purpose too (the design's): Book Club is three rounds ahead
  // of you, The Cousins closed a round at its deadline with someone absent,
  // and the other two are level. `phase` staggers the rating round per room
  // (never round 1 — the live app's groupPhase is a hash mod 3 for the same
  // reason); gBase() offsets each room into the pool so the packs do not
  // march in step.
  const GROUPS = [
    { id: 'g1', name: 'The Crew', ids: ['f1', 'f2', 'f4', 'f6', 'f3', 'f12', 'f14'], phase: 0 },
    { id: 'g2', name: 'Book Club', ids: ['f2', 'f3', 'f6', 'f22'], ahead: 3, phase: 1 },
    { id: 'g3', name: 'The Cousins', ids: ['f1', 'f4'], closed: true, phase: 2 },
    { id: 'g4', name: 'The Long Table', ids: ['f2', 'f6', 'f8', 'f10', 'f9'], phase: 1 },
  ];
  // the seeded history: this many rounds revealed before you opened the app
  const HIST_G = 11;
  // seeded (minus left, with member edits) + your custom groups
  function groupDefs() {
    const seeded = GROUPS.filter((g) => !S.left.includes(g.id)).map((g) => ({ ...g, ids: S.groupIds[g.id] || g.ids }));
    const custom = S.myGroups.filter((g) => !S.left.includes(g.id)).map((g) => ({ ...g, custom: true }));
    return seeded.concat(custom);
  }
  const groupDef = (gid) => groupDefs().find((g) => g.id === gid);
  function setIds(gid, ids) {
    const c = S.myGroups.find((g) => g.id === gid);
    if (c) c.ids = ids; else S.groupIds[gid] = ids;
  }
  const gBase = (gid) => {
    const si = GROUPS.findIndex((g) => g.id === gid);
    return si >= 0 ? si * 3 : Math.floor(h01('gb' + gid) * Math.max(ALL_ROLES.length, 1));
  };
  const gPhase = (gid) => {
    const G = GROUPS.find((g) => g.id === gid);
    return G ? (G.phase || 0) : Math.floor(h01('ph' + gid) * 3);
  };
  // custom groups start now — no fake history
  const gHist = (gid) => { const G = groupDef(gid); return G && G.custom ? 0 : HIST_G; };
  const isRatingRound = (gid, r) => (r + gPhase(gid)) % 4 === 0;
  function groupMembers(gid) {
    const G = groupDef(gid); if (!G) return [];
    const pend = S.groupPend[gid] || {};
    return G.ids.map((id) => { const p = personOf(id); return p ? (pend[id] != null ? { ...p, pending: true } : p) : null; }).filter(Boolean);
  }
  const activeMembers = (gid) => groupMembers(gid).filter((p) => !p.pending);
  // the question of a round: a rating on the fourth (by phase), a role vote
  // otherwise, each walking its own pool by how many of its kind came before
  function groupQ(gid, r) {
    const ph = gPhase(gid);
    const ratingsBefore = Math.floor((r - 1 + ph) / 4);
    if (isRatingRound(gid, r) && RATE_QS.length) {
      const q = RATE_QS[(gBase(gid) + ratingsBefore) % RATE_QS.length];
      return { id: 'rate:' + q.id, kind: 'rate', dim: q.dim, prompt: q.prompt, poles: q.poles, options: stepLabels(q.poles) };
    }
    const role = ALL_ROLES[(gBase(gid) + (r - 1 - ratingsBefore)) % ALL_ROLES.length];
    const act = activeMembers(gid);
    return {
      id: 'vote:' + role.key, kind: 'vote', role, scen: role.scen, prompt: role.prompt,
      options: act.map((p) => first(p)).concat('You'),
      targets: act.map((p) => p.id).concat('me'),
    };
  }
  // a member's (mock) answer — a rating clusters around a per-room mean; a
  // role vote leans toward a per-(room, role) favourite, never yourself
  function memberAnswer(gid, r, pid) {
    const q = groupQ(gid, r);
    if (q.kind === 'rate') {
      const c = h01('gc' + gid + q.dim) * 4;
      return Math.max(0, Math.min(4, Math.round(c + (h01('gj' + gid + r + pid) - 0.5) * 2.4)));
    }
    const T = q.targets, k = q.role.key;
    const fav = T[Math.floor(h01('rf' + gid + k) * T.length)];
    if (pid !== fav && h01('rv' + gid + k + pid) < 0.62) return T.indexOf(fav);
    const others = T.filter((id) => id !== pid);
    return T.indexOf(others[Math.floor(h01('rw' + gid + k + pid) * others.length)]);
  }
  // your stored answer to a round — null when the question has moved on
  // (a member joined and the ballot grew, a pool changed under a stored
  // index): the stored qid is the receipt (VISION-2026-09-09 §1.4)
  const gState = (gid, r) => {
    const s = (S.groups[gid] || {})[r];
    if (!s) return null;
    const q = groupQ(gid, r);
    return (s.qid == null || s.qid === q.id) && (s.a == null || s.a < q.options.length) ? s : null;
  };
  function groupDeadline(gid, r) {
    const G = groupDef(gid);
    const hist = gHist(gid);
    if (r <= hist) return null;
    if (G && G.closed && r === hist + 1) return S.epoch - 2 * HOUR;
    return S.epoch + (r - hist) * DEADLINE + Math.floor(h01('gdl' + gid + r) * 6) * HOUR;
  }
  const groupClosed = (gid, r) => { const d = groupDeadline(gid, r); return d != null && Date.now() >= d; };
  function memberIn(gid, r, pid) {
    const G = groupDef(gid); if (!G) return false;
    const hist = gHist(gid);
    if (r <= hist) return true;
    if ((S.groupIn[gid] || {})[r] && S.groupIn[gid][r][pid] != null) return true;
    if (G.ahead && r - hist <= G.ahead) return true;
    if (G.closed && r === hist + 1) {
      const act = activeMembers(gid);
      const absent = act[Math.floor(h01('gabs' + gid) * act.length)];
      return !absent || absent.id !== pid;
    }
    return h01('gi' + gid + r + pid) < 0.6;
  }
  const myIn = (gid, r) => r <= gHist(gid) || !!(gState(gid, r) && gState(gid, r).a != null);
  const allIn = (gid, r) => activeMembers(gid).every((p) => memberIn(gid, r, p.id));
  const groupRevealed = (gid, r) => r <= gHist(gid) || (myIn(gid, r) && allIn(gid, r)) || groupClosed(gid, r);
  function groupRevealedCount(gid) {
    let r = gHist(gid);
    while (groupRevealed(gid, r + 1)) r++;
    return r;
  }
  const groupMyTop = (gid) => { let r = gHist(gid); while (myIn(gid, r + 1)) r++; return r; };
  const groupTheirTop = (gid) => { let r = gHist(gid); while (activeMembers(gid).length && allIn(gid, r + 1)) r++; return r; };
  // the round in front of you, or null at the lead's edge
  function groupOpen(gid) {
    const mine = groupMyTop(gid), theirs = groupTheirTop(gid);
    if (mine - theirs >= LEAD) return null;
    return mine + 1;
  }
  function myGroupRound(gid, r) {
    if (r <= gHist(gid)) return { a: memberAnswer(gid, r, 'me'), late: false };
    const s = gState(gid, r);
    return { a: s ? s.a : null, late: !!(s && s.late) };
  }
  function answerGroup(gid, i, r) {
    r = r || groupOpen(gid);
    if (!r) return;
    const late = groupClosed(gid, r);
    S.groups[gid] = { ...(S.groups[gid] || {}), [r]: { ...(gState(gid, r) || {}), a: i, late, qid: groupQ(gid, r).id } };
    if (!late && !allIn(gid, r)) {
      S.groupDue[gid] = S.groupDue[gid] || {};
      S.groupDue[gid][r] = S.groupDue[gid][r] || {};
      activeMembers(gid).forEach((p) => {
        if (!memberIn(gid, r, p.id)) S.groupDue[gid][r][p.id] = Date.now() + 12000 + Math.floor(h01('glag' + gid + r + p.id) * 40000);
      });
      ensureTimer();
    }
    save();
  }
  function groupDone(gid) {
    if (gid) return groupOpen(gid) == null;
    return groupDefs().every((g) => groupDone(g.id));
  }
  function groupsPending() { return groupDefs().filter((g) => !groupDone(g.id)).length; }
  // who has already played the round in front of you
  function groupInToday(gid) {
    const r = groupOpen(gid) || groupMyTop(gid);
    const act = activeMembers(gid);
    return { done: act.filter((p) => memberIn(gid, r, p.id)).map((p) => p.id), total: act.length + 1, round: r };
  }
  // a round's reveal: option → people (you included), the holder of a role
  // vote, the mean of a rating — never a majority, never a call
  function groupPicksRound(gid, r) {
    const q = groupQ(gid, r);
    const rows = q.options.map((label, oi) => ({ label, oi, who: [] }));
    const act = activeMembers(gid);
    const played = act.filter((p) => memberIn(gid, r, p.id));
    played.forEach((p) => rows[memberAnswer(gid, r, p.id)].who.push(p));
    const my = myGroupRound(gid, r);
    const mine = my.a;
    const counts = rows.map((row) => row.who.length + (mine === row.oi && !my.late ? 1 : 0));
    const total = counts.reduce((a, b) => a + b, 0);
    const out = {
      q, r, rows, mine, late: my.late, counts, total, played,
      absent: act.length - played.length, closed: groupClosed(gid, r), revealed: groupRevealed(gid, r),
    };
    if (q.kind === 'vote') {
      const order = q.targets.map((_, i) => i).sort((a, b) => counts[b] - counts[a] || a - b);
      const win = order[0], sec = order.length > 1 ? order[1] : null;
      out.winner = q.targets[win];
      out.second = sec != null && counts[sec] > 0 ? q.targets[sec] : null;
      out.contested = out.second != null && counts[sec] >= 2 && counts[win] - counts[sec] <= 1;
      out.votes = {};
      // …and the votes RECEIVED: the same counts less a vote for yourself,
      // which is not the room naming you — the live instrument's rule
      // (`seatTally`, D435). The card keeps every vote; the seat reads these.
      out.received = {};
      q.targets.forEach((id, i) => {
        out.votes[id] = counts[i];
        const self = id === 'me'
          ? (mine === i && !my.late)
          : (played.some((p) => p.id === id) && memberAnswer(gid, r, id) === i);
        out.received[id] = counts[i] - (self ? 1 : 0);
      });
      out.people = q.targets.map((id) => (id === 'me' ? { id: 'me', me: true } : act.find((p) => p.id === id)));
    } else {
      out.mean = total ? counts.reduce((s, c, i) => s + c * i, 0) / total : 2;
      out.score = Math.round((out.mean / 4) * 100);
    }
    return out;
  }
  // how often the rooms named you, over every revealed role vote — the
  // Map's People branch reads it (crowns/votes, and the two older names)
  function groupAlignment() {
    let crowns = 0, votes = 0;
    groupDefs().forEach((G) => {
      const n = groupRevealedCount(G.id);
      for (let r = 1; r <= n; r++) {
        if (isRatingRound(G.id, r)) continue;
        const g = groupPicksRound(G.id, r);
        if (!g.total) continue;
        votes++; if (g.winner === 'me') crowns++;
      }
    });
    return { crowns, votes, withMaj: crowns, total: votes };
  }
  // the room's record — who names whom, and whoever casts the room like you
  function groupPortrait(gid) {
    const ms = groupMembers(gid);
    const withMe = {}, crowns = { me: 0 }, named = { me: 0 };
    ms.forEach((p) => { withMe[p.id] = 0; crowns[p.id] = 0; named[p.id] = 0; });
    let meCrowns = 0;
    const voteRounds = [], rateRounds = [];
    const n = groupRevealedCount(gid);
    for (let r = 1; r <= n; r++) {
      if (isRatingRound(gid, r)) { rateRounds.push(r); continue; }
      const g = groupPicksRound(gid, r);
      if (!g.total) continue;
      voteRounds.push(r);
      const mine = g.late ? null : g.mine;
      if (g.winner === 'me') meCrowns++;
      if (crowns[g.winner] != null) crowns[g.winner]++;
      g.q.targets.forEach((id, i) => { if (named[id] != null) named[id] += g.counts[i]; });
      ms.forEach((p) => {
        if (p.pending || !memberIn(gid, r, p.id)) return;
        if (mine != null && memberAnswer(gid, r, p.id) === mine) withMe[p.id]++;
      });
    }
    const act = ms.filter((p) => !p.pending);
    const twin = act.slice().sort((a, b) => withMe[b.id] - withMe[a.id])[0] || null;
    return { rounds: n, votes: voteRounds.length, ratings: rateRounds.length, voteRounds, rateRounds, meCrowns, crowns, named, twin, withMe };
  }
  // who the room named, role by role — the latest vote on each
  function roleVotes(gid) {
    const targets = activeMembers(gid).map((p) => p.id).concat('me');
    const byKey = new Map();
    const n = groupRevealedCount(gid);
    for (let r = 1; r <= n; r++) {
      if (isRatingRound(gid, r)) continue;
      const g = groupPicksRound(gid, r);
      if (!g.total) continue;
      const order = g.q.targets.slice().sort((a, b) => g.votes[b] - g.votes[a]);
      byKey.set(g.q.role.key, { ...g.q.role, r, votes: g.votes, received: g.received, order, winner: g.winner, second: g.second, contested: g.contested });
    }
    return { scenarios: SCENARIOS, roles: [...byKey.values()], targets };
  }
  // a member's seat: the share of the votes they received per seat (D435)
  function archetypeOf(gid, id) {
    const rv = roleVotes(gid);
    const shares = { engine: 0, hands: 0, heart: 0, wild: 0 };
    const won = { engine: [], hands: [], heart: [], wild: [] };
    let total = 0;
    rv.roles.forEach((role) => {
      // votes received — never your own (the second review of #456 could
      // earn a seat on the demo by naming itself twice)
      const v = (role.received || role.votes)[id] || 0;
      if (shares[role.seat] == null) return;
      shares[role.seat] += v; total += v;
      if (role.winner === id || (role.contested && role.second === id)) won[role.seat].push(role);
    });
    const pct = {};
    SEATS.forEach((s) => { pct[s.id] = total ? Math.round((shares[s.id] / total) * 100) : 0; });
    const seat = total ? SEATS.slice().sort((a, b) => shares[b.id] - shares[a.id] || won[b.id].length - won[a.id].length)[0] : null;
    return { seat, shares, pct, total, won, roles: rv.roles.length };
  }
  // how the group rates itself — one row per rated dim, the latest answer
  function groupScores(gid) {
    const byDim = new Map();
    const n = groupRevealedCount(gid);
    for (let r = 1; r <= n; r++) {
      if (!isRatingRound(gid, r)) continue;
      const g = groupPicksRound(gid, r);
      if (!g.total) continue;
      const marks = [];
      g.rows.forEach((row) => row.who.forEach((p) => marks.push({ id: p.id, p, step: row.oi })));
      if (g.mine != null && !g.late) marks.push({ id: 'me', me: true, step: g.mine });
      byDim.set(g.q.dim, {
        dim: g.q.dim, prompt: g.q.prompt, poles: g.q.poles, r, marks,
        mine: g.late ? null : g.mine, mean: g.mean, score: g.score, counts: g.counts, total: g.total,
        label: stepLabel(g.q.poles, Math.round(g.mean)),
      });
    }
    return [...byDim.values()];
  }
  // everything the card needs, per group
  function groupView(gid) {
    const hist = gHist(gid), revealed = groupRevealedCount(gid);
    const open = groupOpen(gid), myTop = groupMyTop(gid), theirTop = groupTheirTop(gid);
    const waiting = Math.max(0, theirTop - myTop);
    const ahead = Math.max(0, myTop - revealed);
    return {
      hist, revealed, open, myTop, theirTop, waiting, ahead,
      lead: open == null,
      openClosed: open != null && groupClosed(gid, open),
      lastRevealed: revealed >= 1 ? groupPicksRound(gid, revealed) : null,
      q: (r) => groupQ(gid, r),
      deadline: (r) => groupDeadline(gid, r),
      picks: (r) => groupPicksRound(gid, r),
      mine: (r) => myGroupRound(gid, r),
      who: (r) => activeMembers(gid).map((p) => ({ ...p, played: memberIn(gid, r, p.id) })),
      sealed: Array.from({ length: ahead }, (_, i) => revealed + 1 + i),
    };
  }
  function groups() {
    return groupDefs().map((g) => ({
      id: g.id, name: g.name, custom: !!g.custom, members: groupMembers(g.id), done: groupDone(g.id),
      waiting: Math.max(0, groupTheirTop(g.id) - groupMyTop(g.id)),
    }));
  }

  // ── group management ────────────────────────────────────────────────────────
  function createGroup(name, ids) {
    const gid = 'c' + Date.now().toString(36);
    S.myGroups.push({ id: gid, name: (name || 'New group').trim(), ids: ids.slice() });
    S.groupPend[gid] = {};
    const now = Date.now();
    ids.forEach((pid) => { S.groupPend[gid][pid] = now; });
    ensureTimer(); save();
    return gid;
  }
  function addGroupMembers(gid, ids) {
    const G = groupDef(gid); if (!G || !ids.length) return;
    setIds(gid, G.ids.concat(ids.filter((id) => !G.ids.includes(id))));
    S.groupPend[gid] = S.groupPend[gid] || {};
    const now = Date.now();
    ids.forEach((pid) => { S.groupPend[gid][pid] = now; });
    ensureTimer(); save();
  }
  function removeGroupMember(gid, pid) {
    const G = groupDef(gid); if (!G) return;
    setIds(gid, G.ids.filter((id) => id !== pid));
    if (S.groupPend[gid]) delete S.groupPend[gid][pid];
    save();
  }
  function leaveGroup(gid) {
    if (!S.left.includes(gid)) S.left.push(gid);
    S.myGroups = S.myGroups.filter((g) => g.id !== gid);
    delete S.groups[gid]; delete S.groupPend[gid]; delete S.groupIds[gid]; delete S.groupIn[gid]; delete S.groupDue[gid];
    save();
  }

  // ── 1v1: answer + guess, revealed when both are in ─────────────────────────
  // Situational reads with observable tells — guessable if you truly know
  // them. Mixed option counts (2–4): more options = a right guess means more.
  // Ordered light → deep in content/duel-questions.json, sampled per domain
  // for the demo (D433) — the sample takes the light end of each domain, so
  // the ladder is shorter here and duoQ's wrap does the rest. The CAST entry
  // of each pool (D435) is the fourth round's question, not part of the
  // ladder.
  const DUO_QS = DUEL_CONTENT.oneVsOne.filter((q) => q.kind !== 'cast');
  // The same game, aimed at a person you share a life with rather than a
  // friend: the tells are domestic, and the deep end is about what happens
  // next. Same shape — light → deep, 2–4 options — so the ladder is identical.
  const DUO_QS_ROMANTIC = DUEL_CONTENT.romantic.filter((q) => q.kind !== 'cast');
  // The cast sets (D435): one entry per pool — "Most days, {name} is…" with
  // four plain answers, each carrying an axis (`dims`) and a *them* form
  // (`them`) for when the fact is said about the other side.
  const CAST_SETS = {
    friends: DUEL_CONTENT.oneVsOne.find((q) => q.kind === 'cast') || null,
    romantic: DUEL_CONTENT.romantic.find((q) => q.kind === 'cast') || null,
  };
  // Three rows, never more: DOMAIN_MIN is 4 correct reads EACH way, so a fourth
  // lens pushes a full chart from ~12 rounds out to ~16 — and three rows read
  // at a glance where five become a table.
  //
  // The third row is mode-specific, because the weak lens differs by relationship.
  // Friends rarely see each other under real pressure and almost never test each
  // other's five-year plan; the live gap between friends is the MIRROR — do you
  // know how they see you. For a partner the future IS the loaded one (money,
  // kids, moving), so romantic keeps 'ahead'.
  const DOMAIN_DEFS = {
    day:    { id: 'day',    label: 'everyday',         noun: 'everyday self' },
    heat:   { id: 'heat',   label: 'under pressure',   noun: 'pressure' },
    ahead:  { id: 'ahead',  label: "what's ahead",     noun: 'future' },
    mirror: { id: 'mirror', label: 'how they see you', noun: 'self-image' },
  };
  const DOMAIN_SET = { friends: ['day', 'heat', 'mirror'], romantic: ['day', 'heat', 'ahead'] };
  const domainsFor = (mode) => DOMAIN_SET[mode === 'romantic' ? 'romantic' : 'friends'].map((k) => DOMAIN_DEFS[k]);
  const DOMAINS = domainsFor('friends');
  const DOMAIN_MIN = 4; // fewer plays than this and the row is absent, not thin
  // qualifying rows only — a row of one dot is noise dressed as insight
  function domainRows(duo) {
    if (!duo || !duo.domains) return [];
    return domainsFor(duo.mode).map((D) => {
      const d = duo.domains[D.id]; if (!d) return null;
      if (d.read.length < DOMAIN_MIN || d.by.length < DOMAIN_MIN) return null;
      return { ...D, read: d.read, by: d.by, byMissed: d.by.filter((x) => !x).length, byRate: d.by.filter((x) => !x).length / d.by.length };
    }).filter(Boolean);
  }
  // the one place they read you worst — only if it CLEARLY stands out. Compared
  // as a RATE: rows hold different numbers of plays, and a raw miss count just
  // names whichever lens has been played most.
  function weakDomain(duo) {
    const rows = domainRows(duo); if (rows.length < 2) return null;
    const s = rows.slice().sort((a, b) => b.byRate - a.byRate);
    return s[0].byRate - s[1].byRate >= 0.2 ? s[0] : null;
  }
  const DUO_POOL = (pid) => (duoMode(pid) === 'romantic' ? DUO_QS_ROMANTIC : DUO_QS);
  function duoMode(pid) { return S.duoMode[pid] === 'romantic' ? 'romantic' : 'friends'; }
  function setDuoMode(pid, mode) { S.duoMode[pid] = mode === 'romantic' ? 'romantic' : 'friends'; save(); }
  // rounds already played (and revealed) with each partner; 0 = never played.
  // A partner absent from these tables is not broken — they read as a
  // never-played pair (state 'start', no history), which is what a freshly
  // accepted 1v1 is. The seeded eight carry a spread instead, because the
  // things that only appear at depth need it: domainRows() hides a lens
  // under DOMAIN_MIN (4 each way), ReadRun switches encoding on the span,
  // castOf needs a cast round to have come, and weakDomain() compares RATES,
  // so a long record and a short one have to coexist for that comparison to
  // mean anything.
  const PLAYED = { f1: 24, f2: 5, f4: 3, f6: 2, f3: 0, f12: 16, f17: 11, f14: 6 };
  // rounds the partner has already answered PAST the revealed ones — the
  // "N rounds waiting for you" band — and how long they take to answer a
  // round after you (null = they never do, the sealed state stays)
  const THEIR_AHEAD = { f1: 1, f2: 0, f4: 3, f6: 0, f3: 0, f12: 0, f17: 2, f14: 0 };
  const LAG = { f1: 14000, f2: 45000, f4: 9000, f6: null, f3: 20000, f12: 11000, f17: 30000, f14: null };
  // how well YOU tend to read them / how well THEY tend to read you
  const READ_SKILL = { f1: 0.85, f2: 0.72, f4: 0.5, f6: 0.34, f3: 0.5, f12: 0.66, f17: 0.45, f14: 0.8 };
  const BY_SKILL = { f1: 0.9, f2: 0.75, f4: 0.4, f6: 0.62, f3: 0.5, f12: 0.72, f17: 0.58, f14: 0.42 };
  // …and it is UNEVEN across domains — the whole point of the split. Without
  // this, per-domain differences are just noise and the record says nothing.
  const DOMAIN_BIAS = {
    f1: { read: { day: 1.1, heat: 1.0, mirror: 0.6, ahead: 0.55 }, by: { day: 1.1, heat: 0.5, mirror: 0.95, ahead: 0.95 } },
    // The second long record, biased the other way round: f1's blind spot is
    // pressure, f12's is the everyday. With only one authored partner every
    // weakDomain() readout on the Map came from the same person, so a bug
    // that hardcoded f1's shape would have looked correct.
    f12: { read: { day: 0.7, heat: 1.15, mirror: 1.0, ahead: 0.9 }, by: { day: 0.25, heat: 1.1, mirror: 1.05, ahead: 0.9 } },
  };
  function bias(pid, side, dom) {
    const b = DOMAIN_BIAS[pid];
    if (b && b[side] && b[side][dom] != null) return b[side][dom];
    return 0.75 + h01('db' + pid + side + dom) * 0.5; // deterministic spread
  }
  const skillFor = (base, pid, side, dom) => Math.max(0.05, Math.min(0.97, (base || 0.5) * bias(pid, side, dom)));
  const dHist = (pid) => PLAYED[pid] || 0;

  // ── the cast round (D435) ───────────────────────────────────────────────────
  // Every fourth round asks what the other is to you: four plain sentences,
  // each an axis. Nothing here is a call; the guess is at what THEY said
  // you are, in the *them* form.
  const castSet = (mode) => CAST_SETS[mode === 'romantic' ? 'romantic' : 'friends'] || CAST_SETS.friends;
  const castThem = (them, name, romantic) => castText(them, name, romantic);
  function castQ(pid, r) {
    const romantic = duoMode(pid) === 'romantic';
    const set = castSet(duoMode(pid));
    const p = personOf(pid);
    const name = p ? first(p) : null;
    return {
      id: 'cast:' + (set ? set.id : 'x') + ':' + r, kind: 'cast', d: 'cast',
      prompt: castText(set ? set.prompt : 'Most days, {name} is…', name, romantic),
      options: set ? set.options : [],
      optionsThem: set ? set.them.map((t) => castText(t, name, romantic)) : [],
      dims: set ? set.dims : [],
      roles: set ? set.options.map((label, i) => ({ id: set.dims[i], dim: set.dims[i], label, them: set.them[i] })) : [],
    };
  }
  // what you are to each other, over the cast rounds that have revealed
  function castOf(pid) {
    const q = castQ(pid, 4);
    const roles = q.roles;
    const n = duoRevealedCount(pid);
    const casts = [];
    for (let r = 4; r <= n; r += 4) {
      const rd = duoRound(pid, r);
      if (rd.q.kind === 'cast') casts.push({ r, mine: rd.myAns, theirs: rd.theirAns, myGuess: rd.myGuess, sawIt: !!rd.readRight });
    }
    const tally = (key) => { const c = roles.map(() => 0); casts.forEach((x) => { if (x[key] != null) c[x[key]]++; }); return c; };
    const top = (c, key) => {
      if (!casts.length) return null;
      const best = Math.max(...c);
      const latest = casts.slice().reverse().find((x) => x[key] != null && c[x[key]] === best);
      return latest ? { role: roles[latest[key]], n: best } : null;
    };
    const theirs = tally('theirs'), mine = tally('mine');
    return {
      roles, casts, n: casts.length, theirs, mine,
      youAre: top(theirs, 'theirs'), theyAre: top(mine, 'mine'),
      sawIt: { right: casts.filter((x) => x.sawIt).length, total: casts.length },
    };
  }

  // active 1v1 pids — seeded to the circle on first run, friends only
  function duoList() { if (!S.duoList) S.duoList = IDS.slice(); return S.duoList; }
  const duoIds = () => duoList().filter((pid) => FRIENDS.isFriend(pid));
  function duoAvailable() { return members().filter((p) => !duoList().includes(p.id) && S.duoInv[p.id] == null); }
  function startDuo(pid) { if (duoList().includes(pid) || S.duoInv[pid] != null) return; S.duoInv[pid] = Date.now(); ensureTimer(); save(); }
  function cancelDuo(pid) { delete S.duoInv[pid]; save(); }
  function endDuo(pid) { S.duoList = duoList().filter((x) => x !== pid); delete S.duoInv[pid]; delete S.duo[pid]; delete S.duoTheirs[pid]; delete S.duoDue[pid]; save(); }

  // the kinds of round: three own, then a cast — the live deck's duoKind
  // (deck.ts) since the owner retired World rounds from the 1v1 (D426's
  // third amendment, confirmed 2026-09-09)
  const duoKind = (r) => (r % 4 === 0 ? 'cast' : 'own');
  // depth ladder: own rounds walk the pool light → deep, skipping the casts;
  // past the deep end, wrap instead of clamping — a long run kept re-serving
  // the last question forever, so late rounds carried no domain
  function duoQ(pid, r) {
    if (duoKind(r) === 'cast') return castQ(pid, r);
    const pool = DUO_POOL(pid);
    const step = r - Math.floor(r / 4) - 1;
    return pool[step < pool.length ? step : pool.length - 1 - (step % pool.length)];
  }
  const dKey = (q) => q.id || q.prompt;
  // your stored answer to a round — null when the question moved (§1.4)
  const dState = (pid, r) => {
    const s = (S.duo[pid] || {})[r];
    if (!s) return null;
    const q = duoQ(pid, r), n = q.options.length;
    return (s.qid == null || s.qid === dKey(q)) && (s.a == null || s.a < n) && (s.g == null || s.g < n) ? s : null;
  };
  const theirsIn = (pid, r) => r <= dHist(pid) + (THEIR_AHEAD[pid] || 0) || !!((S.duoTheirs[pid] || {})[r] != null);
  const mineIn = (pid, r) => {
    if (r <= dHist(pid)) return true;
    const s = dState(pid, r);
    return !!(s && s.a != null && s.g != null);
  };
  const duoRevealed = (pid, r) => r <= dHist(pid) || (mineIn(pid, r) && theirsIn(pid, r));
  function duoRevealedCount(pid) { let r = dHist(pid); while (duoRevealed(pid, r + 1)) r++; return r; }
  const duoMyTop = (pid) => { let r = dHist(pid); while (mineIn(pid, r + 1)) r++; return r; };
  const duoTheirTop = (pid) => { let r = dHist(pid); while (theirsIn(pid, r + 1)) r++; return r; };
  function duoOpen(pid) {
    const mine = duoMyTop(pid);
    return mine - duoTheirTop(pid) >= LEAD ? null : mine + 1;
  }
  // one round; the partner's answer and guess are deterministic mock, yours
  // come from storage past the seeded history
  function duoRound(pid, r) {
    const q = duoQ(pid, r);
    const key = pid + ':r' + r;
    const n = q.options.length;
    const wrong = (right, k) => (right + 1 + Math.floor(h01(k) * (n - 1))) % n; // any option but the right one
    const hist = r <= dHist(pid);
    const cast = q.kind === 'cast';
    // a cast answer is sticky: most rounds they say the same thing about you
    const sticky = (who) => {
      const fav = Math.floor(h01('cf' + who + pid) * n);
      return h01('cs' + who + key) < 0.72 ? fav : (fav + 1 + Math.floor(h01('cx' + who + key) * (n - 1))) % n;
    };
    const theirAns = cast ? sticky('t') : Math.floor(h01('ta' + key) * n);
    const s = dState(pid, r) || {};
    const myAns = hist ? (cast ? sticky('m') : Math.floor(h01('da' + key) * n)) : (s.a != null ? s.a : null);
    const myGuess = hist
      ? (h01('dg' + key) < skillFor(READ_SKILL[pid], pid, 'read', q.d) ? theirAns : wrong(theirAns, 'dgw' + key))
      : (s.g != null ? s.g : null);
    const revealed = duoRevealed(pid, r);
    const theirGuess = revealed && myAns != null
      ? (h01('tg' + key) < skillFor(BY_SKILL[pid], pid, 'by', q.d) ? myAns : wrong(myAns, 'tgw' + key))
      : null;
    return {
      q, r, myAns, myGuess, theirAns, theirGuess, revealed,
      mineIn: mineIn(pid, r), theirsIn: theirsIn(pid, r),
      readRight: revealed && myGuess === theirAns,
      byRight: revealed && theirGuess != null && theirGuess === myAns,
    };
  }
  // the older index shape the Map and the person page read: idx 0 = the
  // round in front of you, idx n = the n-th most recent revealed round
  function duoDay(pid, idx) {
    return duoRound(pid, idx === 0 ? (duoOpen(pid) || duoMyTop(pid) + 1) : duoRevealedCount(pid) - idx + 1);
  }
  function myDuo(pid) { const r = duoOpen(pid); return r ? (dState(pid, r) || {}) : {}; }
  function answerDuo(pid, patch, r) {
    r = r || duoOpen(pid);
    if (!r) return;
    S.duo[pid] = { ...(S.duo[pid] || {}), [r]: { ...(dState(pid, r) || {}), ...patch, qid: dKey(duoQ(pid, r)) } };
    if (mineIn(pid, r) && !theirsIn(pid, r) && LAG[pid] != null) {
      S.duoDue[pid] = S.duoDue[pid] || {};
      S.duoDue[pid][r] = Date.now() + LAG[pid];
      ensureTimer();
    }
    save();
  }
  const partnerToday = (pid) => theirsIn(pid, duoOpen(pid) || duoMyTop(pid));
  function duoState(pid) {
    const open = duoOpen(pid);
    if (open != null) return duoRevealedCount(pid) === 0 && open === 1 ? 'start' : 'turn';
    return 'waiting';
  }
  // everything the card needs, per partner
  function duoView(pid) {
    const hist = dHist(pid), revealed = duoRevealedCount(pid);
    const open = duoOpen(pid), myTop = duoMyTop(pid), theirTop = duoTheirTop(pid);
    const ahead = Math.max(0, myTop - revealed);
    return {
      hist, revealed, open, myTop, theirTop,
      waiting: Math.max(0, theirTop - myTop), ahead,
      lead: open == null,
      lastRevealed: revealed >= 1 ? duoRound(pid, revealed) : null,
      round: (r) => duoRound(pid, r),
      sealed: Array.from({ length: ahead }, (_, i) => revealed + 1 + i),
    };
  }
  // everything the UI and the map need, per partner (invites last)
  function partners() {
    const live = duoIds().map((pid) => personOf(pid)).filter(Boolean).map((p) => {
      const played = duoRevealedCount(p.id);
      const read = { right: 0, total: 0 };
      const readBy = { right: 0, total: 0 };
      const misses = []; // where THEY misread YOU — your impression gap
      // the same tally split by what the question was ABOUT: which parts of
      // each other you actually read. Gated in the UI until deep enough.
      const domains = {}; domainsFor(duoMode(p.id)).forEach((k) => { domains[k.id] = { read: [], by: [] }; });
      for (let r = 1; r <= played; r++) {
        const rd = duoRound(p.id, r);
        read.total++; if (rd.readRight) read.right++;
        readBy.total++; if (rd.byRight) readBy.right++;
        const dm = domains[rd.q.d];
        if (dm) { dm.read.push(!!rd.readRight); dm.by.push(!!rd.byRight); }
        if (!rd.byRight) {
          misses.push({ pid: p.id, name: p.name, dayIdx: played - r + 1, round: r, q: rd.q.prompt, guessed: rd.q.options[rd.theirGuess], actual: rd.q.options[rd.myAns] });
        }
      }
      const state = duoState(p.id);
      const v = duoView(p.id);
      return { ...p, played, read, readBy, domains, misses, state, streak: played, rounds: played, waiting: v.waiting, ahead: v.ahead, open: v.open, mode: duoMode(p.id) };
    });
    const invited = Object.keys(S.duoInv).map((pid) => personOf(pid)).filter(Boolean)
      .map((p) => ({ ...p, played: 0, read: { right: 0, total: 0 }, readBy: { right: 0, total: 0 }, domains: null, misses: [], state: 'invited', streak: 0, rounds: 0, waiting: 0, ahead: 0, open: null, mode: duoMode(p.id) }));
    return live.concat(invited);
  }
  function pendingDuos() { return partners().filter((p) => p.state === 'turn' || p.state === 'start').length; }
  // where your people misread you, freshest first — the "how they see you" gap
  function impressions() {
    return partners().flatMap((p) => p.misses).sort((a, b) => a.dayIdx - b.dayIdx);
  }

  function resetRounds() {
    S.duo = {}; S.duoTheirs = {}; S.duoDue = {};
    S.groups = {}; S.groupIn = {}; S.groupDue = {};
    save();
  }
  // "2d 5h", "5h 20m", "40m" — what is left before a deadline
  function fmtLeft(ms) {
    if (ms == null) return '';
    const m = Math.max(0, Math.round(ms / 60000));
    if (m < 1) return 'under a minute';
    const d = Math.floor(m / 1440), h = Math.floor((m % 1440) / 60);
    if (d > 0) return d + 'd ' + h + 'h';
    return h > 0 ? h + 'h ' + String(m % 60).padStart(2, '0') + 'm' : m + 'm';
  }

  DUELS = {
    LEAD, members, personOf, first, fmtLeft,
    isRatingRound, stepLabel, duoKind,
    groups, groupQ, groupMembers, groupPicksRound, groupView, myGroupRound, answerGroup, groupDone, groupsPending, groupInToday,
    groupAlignment, groupPortrait, groupScores, groupDeadline, groupOpen,
    createGroup, addGroupMembers, removeGroupMember, leaveGroup,
    SCENARIOS, ALL_ROLES, RATE_QS, SEATS, seatOf, roleVotes, archetypeOf,
    CAST_SETS, castQ, castThem, castOf,
    duoQ, duoDay, duoRound, duoView, duoOpen, myDuo, answerDuo, partnerToday, duoState, partners, pendingDuos, impressions,
    duoMode, setDuoMode, DOMAINS, domainsFor, domainRows, weakDomain,
    duoAvailable, startDuo, cancelDuo, endDuo,
    resetRounds, resetToday: resetRounds,
    subscribe: (f) => { listeners.add(f); return () => listeners.delete(f); },
  };
  // circle changes (befriend / unfriend) ripple into duos & groups
  FRIENDS.subscribe(fire);
})();
