// Ported from design/InSight_standalone_15.html (learn-data.js, 2026-07-31
// revision). THIS file is the live source of the BEHAVIOR; the card bank
// itself moved to content/learn-questions.json when Learn went live (D32) —
// one source feeds both this module and the seeded Firestore bank via
// scripts/gen-v2content.mjs, so the demo cards and the live docs can never
// drift apart. (A static JSON import, not a cross-module import — the spec
// layer's no-imports convention bans load-order coupling between modules,
// which data has none of.)
// OFF THE GLOBAL BRIDGE (D109): the five names below are named exports.
// `learn-progress.js` reads three of them at MODULE SCOPE, so before this
// change the whole Learn mode rested on spec-index.js listing this file one
// line above that one — reorder those two and the card bank is silently
// empty, with no error anywhere. That ordering is now a module-graph
// guarantee, which is the same fragility the `daily-questions.js` conversion
// removed for `map-branches.js`. The store is an import too since D354 —
// read at CALL time in learnLive()/LEARN_COUNTS, never while evaluating.
import { sharePcts } from '../data/pct';
import LIVE from '../data/live';
// The DEMO SAMPLE, not the bank (D284). This import used to be
// `learn-questions.json` — the whole thing — so every learn card was
// compiled into the app and `check:bundle` was about thirty-nine cards from
// failing. The sample is five cards a field, generated by
// `scripts/gen-learn-sample.mjs` and held equal to its source by
// `check:learn-sample`; a live build reads the seeded bank instead, through
// `data/learnBank.ts`. The subjects and fields below are the taxonomy and
// still ship whole — 1 KiB, and they do not grow with the lane.
import LEARN_CONTENT from '../../../content/learn-sample.json';

// learn-data.js — the Learn mode's content. Three levels of nesting, and only
// the bottom two are taxonomy: Learn is the MODE (a question with a right
// answer), subject is tier 2 (Biology), field is tier 3 (Cell biology). That
// reuses the topic → subtopic shape the World feed already has, so nothing in
// the existing taxonomy has to bend.
//
// A card carries:
//   q  the question · a  the options · c  index of the correct one
//   t  index of the TRAP — the wrong answer people actually pick. This is what
//      makes a knowledge question an InSight question: the split of wrong
//      answers is a map of common misconceptions, not noise.
//   p  % of the crowd who get it right. Doubles as difficulty (low p = hard),
//      so "on your level" runs on real crowd data, not invented 1–5 labels.
//   k  the fact in three words — the label the mastered dot wears on your map.
//   w  optional one line of why. Only where the fact is genuinely counter-
//      intuitive; never an argument, never more than ~20 words.

export const LEARN_SUBJECTS = LEARN_CONTENT.subjects;

export const LEARN_FIELDS = LEARN_CONTENT.fields;

// The demo sample. Every consumer reads it through `LEARN` (the engine),
// which swaps in the live bank when one is published — so this export is
// the FALLBACK rather than the bank, and the name is kept because the
// alternative was renaming it at nine call sites to say the same thing.
export const LEARN_CARDS = LEARN_CONTENT.cards;

// ── the display order ───────────────────────────────────────────────────────
// MEASURED 2026-08-12, and it was a shipped defect rather than a nicety: the
// correct answer was authored at index 0 on all 96 cards then in the bank, and
// the trap at index 1 on 79 of them. Nothing shuffled — renderKnow mapped
// `card.a` straight down the screen — so "tap the top option" scored 100% and
// Learn tested reading position, not knowledge. That also quietly voided the
// measurement the whole mode rests on: D32 promises the reveal's split IS the
// crowd's real first-attempt rate once the aggregate lands, and a crowd tapping
// a free win measures nothing. The scorecard's calibration section (authored
// `p` vs measured) would have graded every card as wildly under-estimated and
// aimed the lane at the wrong fix.
//
// Cards written since vary their `c`, which is belt and braces rather than the
// fix — the permutation is what makes authored position invisible either way,
// and a bank with varied indices merely degrades instead of collapsing if this
// function is ever removed.
//
// Why permute at RENDER rather than re-author `c` across the bank: answers are
// stored as (qid, optionIdx) forever — `learn-<id>` docs whose `counts` are
// keyed by the authored index — so reordering an `a` array silently re-keys
// every answer already given and every aggregate cell built from them. That is
// the D30 re-key failure class the farm manual bans by name, and re-authoring
// 96 cards would be it ninety-six times over. A permutation applied on the way
// to the screen leaves the stored key space untouched: the buttons map back to
// authored indices before anything is recorded.
//
// Deterministic from the card id, like LEARN_SPLIT's own hash below, for the
// reason result-card.jsx gives for its scatter: a stable order means a card
// re-served by the scheduler (the spaced repeat, the check-in) does not
// rearrange itself under a returning reader, and tests can pin it. Stability
// costs nothing here — the tell was positional across the BANK, and a
// per-card permutation is what breaks that.
function learnHash(id) {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  // Avalanche before use. The ×31 accumulator is the one LEARN_SPLIT already
  // uses and it is fine as a bucket hash, but near-identical ids ("cell1",
  // "cell2") land on near-identical seeds, and one xorshift round from
  // near-identical seeds is not one round from independent ones: a 20k sweep
  // over sequential synthetic ids drew slot 3 at 28% against an expected 25%
  // before this line and 25.0% after. The real bank is flat either way — this
  // holds as the bank grows into id runs longer than today's eight per field.
  h ^= h >>> 16; h = Math.imul(h, 0x7feb352d) >>> 0;
  h ^= h >>> 15; h = Math.imul(h, 0x846ca68b) >>> 0;
  return (h ^ (h >>> 16)) >>> 0;
}
export function LEARN_ORDER(card) {
  const n = card.a.length;
  const order = [];
  for (let i = 0; i < n; i++) order.push(i);
  // Fisher–Yates, stepping xorshift32 and drawing from the HIGH bits. Both
  // details are measured, not taste. The first draft stepped an LCG and took
  // `h % (i + 1)`: an LCG modulo 2^32 has period 2 in its lowest bit, so the
  // final swap (j = h % 2) fired on every card regardless of the seed, and
  // the correct answer landed in slot 0 exactly 0 times out of 96 — "never
  // tap the top", which is the same exploitable tell as the one being fixed,
  // just inverted. xorshift32 mixes all 32 bits and the high-bit draw avoids
  // the low-bit structure modulo has to trust.
  let h = learnHash(card.id) || 1; // xorshift32 is a fixed point at 0
  for (let i = n - 1; i > 0; i--) {
    h ^= h << 13; h >>>= 0;
    h ^= h >>> 17;
    h ^= h << 5; h >>>= 0;
    const j = Math.floor((h / 0x100000000) * (i + 1));
    const tmp = order[i];
    order[i] = order[j];
    order[j] = tmp;
  }
  return order;
}

// ── the crowd split ─────────────────────────────────────────────────────────
// Two sources, one seam (D32) — and since D149 the LIVE build has only one
// of them.
//
// The seam was: use the published aggregate when there is one, otherwise
// fall back to the authored model below (correct takes p%, the rest goes
// mostly to the trap), labelled "our estimate" so it never passes as
// measured. Honest, and still the wrong thing to draw. `p` is a
// content-authoring difficulty hint — a number a writer typed while
// writing the card — and rendering it as a bar chart of what other people
// answered makes it look like a reading of a crowd no matter what the
// footer says. A reader does not read the footer; they read the bars.
//
// So in live mode the estimate is gone. A card with no answers behind it
// yet says exactly that, and a card with answers shows HOW MANY people
// picked each option — counts, not just shares, because "31 people picked
// this" is a fact and "62%" of an unstated denominator is halfway back to
// the estimate. The demo build keeps the authored model: there the
// fabricated crowd IS the content, and there is no aggregate to replace it.
// The store, read at CALL time. ONE reference site on purpose: this is the
// file's only shared-global coupling (see the header), so the two readers
// below go through this rather than each reaching for the name — which is
// what keeps check:globals rule 4 flat across D149, and leaves exactly one
// line for the LIVE conversion to take.
function learnLive() {
  return LIVE.enabled;
}
/**
 * The real per-option counts, or null when nothing has been measured.
 *
 * `card.c` and the aggregate's cells are keyed the same way: LEARN_ORDER
 * permutes on the way to the SCREEN and the buttons map back to authored
 * indices before anything is recorded (see its note above).
 *
 * YOUR OWN ANSWER IS IN HERE EVEN WHEN THE AGGREGATE HAS NOT CAUGHT UP
 * (D157). `learnAnswer` writes the answer and re-reads the aggregate in
 * the same breath, and it loses that race to the Firestore trigger far
 * more often than it wins — so the reveal you are looking at, a beat
 * after tapping, drew the crowd MINUS you. On a young card that is not a
 * rounding error: it is what put "0 people · 0%" next to a tick on the
 * option the reader had just chosen. `learnMine` says whether the doc
 * counts you; where it does not, the one answer the client knows for
 * certain exists is added here.
 *
 * Only ever +1, and only ever on a card this session wrote: a repeat
 * cannot reach `learnAnswer` (the scheduler's retries stay device-local
 * and the create-only rule refuses them anyway), so there is no path
 * where this adds a second copy of the same person.
 */
export function LEARN_COUNTS(card) {
  if (!LIVE.enabled) return null;
  const agg = LIVE.learnAgg(card.id);
  if (!agg || !agg.counts) return null;
  const mine = LIVE.learnMine(card.id);
  const pending = mine && !mine.folded ? mine.idx : -1;
  const n = card.a.length;
  const counts = [];
  let total = 0;
  for (let i = 0; i < n; i++) {
    const c = Number(agg.counts[String(i)] || 0) + (i === pending ? 1 : 0);
    counts.push(c);
    total += c;
  }
  if (total <= 0) return null;
  return { counts, total };
}
function learnMeasured(card) {
  const m = LEARN_COUNTS(card);
  if (!m) return null;
  // ONE ROUNDING RULE (data/pct.ts). This floored each share and then
  // handed the leftover points out round-robin FROM INDEX 0, which is not
  // largest-remainder: the extra points go to whichever options happen to
  // come first rather than to the ones closest to their next whole point.
  // Over 200k sampled 3–4 option vectors that printed a smaller count at a
  // larger percentage 4,390 times and put the biggest share on an option
  // fewer people picked 1,904 times — [203, 368, 305, 369] came out
  // [17, 30, 24, 29], so 368 people read as 30% beside 369 people at 29%.
  //
  // These numbers are not decoration: they drive the "X% get this right"
  // headline on the reveal, the crowd row in the card's own sheet and the
  // Map node, printed beside the true counts they contradict. Third site
  // of the same retired rule — the Mirror's and the feed's converted with
  // pct.ts, the daily's on 2026-08-25, this one now.
  return sharePcts(m.counts);
}
/**
 * Which source a card's numbers come from: 'measured', or 'none' in a live
 * build with nothing published yet. Never 'estimate' in live mode — the
 * estimate does not render there at all, so a label for it would describe
 * something that is not on screen.
 */
/**
 * Is the card's aggregate still being read?
 *
 * Only ever true in a live build — the demo has nothing to fetch — and
 * only between the first render that asks for the card and the read
 * coming back. It exists because `null` from the store used to mean both
 * "in the air" and "nobody has answered", and two surfaces printed the
 * second sentence for the first.
 */
function learnLoading(card) {
  // The store is the imported binding (D354), so the `L &&` and the
  // `L.learnAggLoading &&` this arrived with are both dead: an import
  // cannot be unset, and `learnAggLoading` is a member live.ts always
  // defines and vote.test.ts pins. The `enabled` check is the data
  // condition and stays.
  return !!(LIVE.enabled && LIVE.learnAggLoading(card.id));
}

export function LEARN_SPLIT_SRC(card) {
  if (learnMeasured(card)) return 'measured';
  if (learnLoading(card)) return 'loading';
  return learnLive() ? 'none' : 'estimate';
}

/**
 * The one number three surfaces outside the reveal want: the share of the
 * crowd who get this card RIGHT, and where it came from.
 *
 * D133. LEARN_SPLIT above is the whole distribution and the reveal reads
 * it carefully — it renders the measurement when there is one and says
 * "our estimate" when there is not. Every OTHER surface read the authored
 * `card.p` directly and printed it as a finished fact: the map node
 * ("84% of people get this right"), the ⓘ sheet's Crowd row, and the
 * "who knows this" panel's headline. So the same card said "our estimate"
 * in the feed and stated a measurement two taps away, and the authored
 * number — a content-authoring difficulty hint — was the one wearing the
 * authority.
 *
 * `card.c` is safe as the index into a measured split: LEARN_ORDER
 * permutes on the way to the SCREEN and the buttons map back to authored
 * indices before anything is recorded (see its note above), so the
 * aggregate's cells are keyed the way the definition is.
 */
export function LEARN_RATE(card) {
  const measured = learnMeasured(card);
  if (measured) return { pct: measured[card.c], src: 'measured' };
  // D149: no authored fallback in a live build. Every caller already had
  // to branch on `src` to label the estimate; they now render absence
  // instead, which is one fewer number on screen and the only one that
  // was not a measurement. `pct` is null rather than 0 so a caller that
  // forgets the check draws nothing readable and fails a test, rather
  // than quietly claiming nobody gets the card right (the D72 shape).
  // A fourth source, and the only one that is not a statement about the
  // card: the read has not come back. `pct` is null here as it is for
  // 'none', so a caller that branches on the number alone still draws
  // nothing — but one that reads `src` can say "counting" instead of
  // "nobody", which is the difference this exists for.
  if (learnLoading(card)) return { pct: null, src: 'loading' };
  if (learnLive()) return { pct: null, src: 'none' };
  return { pct: card.p, src: 'estimate' };
}
/**
 * Where a mastered fact's dot sits on the Map: 0 is the outer edge, 1 the
 * centre, and `map-layout` turns it into a ±80px radial push.
 *
 * A POSITION IS A CLAIM, so this may only be a MEASUREMENT. map-tab.jsx
 * used to pass `card.p / 100` — the authoring hint, "the % of the crowd
 * expected to get it right", chosen by whoever wrote the card — so on a
 * live build the dot's distance from You was a guess, while the card that
 * opens on tapping that same dot says "Nobody else has answered this one
 * yet" (LEARN_RATE returns `estimate` only when LIVE is off). The daily
 * branch beside it already refuses exactly this and takes the neutral
 * radius instead.
 *
 * `estimate` is kept because it cannot occur on a live build: in the demo
 * every number on the map is the demo's own, and flattening its learn
 * dots would trade one honest map for a duller one.
 */
export function LEARN_TYP(card) {
  const rate = LEARN_RATE(card);
  const usable = rate.src === 'measured' || rate.src === 'estimate';
  return usable && rate.pct != null ? rate.pct / 100 : 0.5;
}

export function LEARN_SPLIT(card) {
  const measured = learnMeasured(card);
  if (measured) return measured;
  if (learnLive()) return null;
  const n = card.a.length;
  let h = 0;
  for (let i = 0; i < card.id.length; i++) h = (h * 31 + card.id.charCodeAt(i)) >>> 0;
  const out = new Array(n).fill(0);
  out[card.c] = card.p;
  let rest = 100 - card.p;
  const wrong = [];
  for (let i = 0; i < n; i++) if (i !== card.c) wrong.push(i);
  const trap = card.t != null && card.t !== card.c ? card.t : wrong[0];
  const trapShare = Math.round(rest * (0.5 + ((h % 18) / 100)));   // 50–68% of the misses
  out[trap] = trapShare;
  rest -= trapShare;
  const others = wrong.filter((i) => i !== trap);
  others.forEach((i, k) => {
    const last = k === others.length - 1;
    const share = last ? rest : Math.round(rest / (others.length - k) * (0.8 + (((h >> (k + 2)) % 40) / 100)));
    out[i] = Math.max(0, Math.min(rest, share));
    rest -= out[i];
  });
  if (rest > 0) out[trap] += rest;
  return out;
}
