// report.mjs — runs the harness at report size and writes REPORT.md.
//
//   node research/sim/report.mjs          prints the report
//   node research/sim/report.mjs --write  also writes research/sim/REPORT.md
//
// Every number here is seeded, so the report is reproducible to the digit;
// the tests beside this file pin the same claims at a size that runs in
// seconds. The report is the evidence a paper may cite for a claim about
// its own statistic; where the report contradicts a paper, the paper
// moves, and the decision record says so.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runIdentificationTable, pairingGraphNullSpace, GRAPHS } from "./identification.mjs";
import { reliability, requiredPairs, reciprocityPower, roundRobinAttenuation } from "./reciprocity.mjs";
import { populationConcordance, coverageExperiment, seScaling, ceilingCurve, shrinkageExperiment, sizingDifference } from "./concordance.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const f3 = (x) => (typeof x === "number" ? x.toFixed(3) : String(x));
const out = [];
const say = (s = "") => out.push(s);

say("# Simulation harness — report");
say();
say("Generated by `node research/sim/report.mjs --write`; every number is seeded and reproduces to the digit. The tests beside this file pin the same claims at a size that runs in seconds. What each section checks is named with the paper and section it checks.");
say();

// ── G7 §3 ──
say("## G7 §3 — the identification table, checked exactly");
say();
say("A variance component is identified on a design if and only if its covariance matrix is linearly independent of the others'. Each row is a design; the null space lists the combinations no estimator separates.");
say();
say("| Design | Obs | Claim | Identified | Unidentified combinations |");
say("| --- | --- | --- | --- | --- |");
for (const r of runIdentificationTable()) {
  say(`| ${r.key} | ${r.observations} | ${r.claim} | ${r.identified.join(", ") || "—"} | ${r.described.join("; ") || "none — all identified"} |`);
}
say();
say("Read against G7 §3: every row holds as the paper states it EXCEPT the context row. A context (group) term shared by several pairs is confounded on groups of three whose units are in no other group; it is identified on groups of four or more with no crossing at all, because two pairs with no member in common share the context and nothing else; and it is identified on groups of three where units cross groups. The paper's row — \"identified only where units cross contexts\" — was too strong and is corrected.");
say();

// ── G7 §4 ──
say("## G7 §4 — what a pairing graph lets a symmetric observation attribute");
say();
say("| Graph | Units | Edges | Bipartite | Difference-type: null dimension | Sum-type: null dimension |");
say("| --- | --- | --- | --- | --- | --- |");
for (const g of GRAPHS) {
  const d = pairingGraphNullSpace(g.units, g.edges, "difference");
  const s = pairingGraphNullSpace(g.units, g.edges, "sum");
  say(`| ${g.key} | ${g.units} | ${g.edges.length} | ${g.bipartite ? "yes" : "no"} | ${d.nullDimension} | ${s.nullDimension} |`);
}
say();
say("Differences leave one constant per connected component; sums leave one alternating constant per bipartite component and nothing where a component has an odd cycle. Both as G7 §4 states, for the fixed part.");
say();

// ── G7 §9 ──
say("## G7 §9 — the reciprocity sizing line");
say();
const R = reliability(1, 1, 2);
say(`Reliability of a relationship term at two replicates per direction, equal variances: ${f3(R)}. Pairs required for r = 0.1 at α = 0.05 two-sided, power 0.8: **${requiredPairs({ r: 0.1 })}** with the terms known exactly, **${requiredPairs({ r: 0.1, R })}** at that reliability.`);
say();
say("| Pairs | r | Reps | Predicted observed r | Mean observed r | Power (sims) |");
say("| --- | --- | --- | --- | --- | --- |");
for (const [nPairs, reps] of [[400, 2], [800, 2], [1200, 2], [1800, 2], [2400, 2], [800, 1000]]) {
  const res = reciprocityPower({ nPairs, r: 0.1, reps, nSim: 600, seed: 31 + nPairs });
  say(`| ${nPairs} | 0.1 | ${reps === 1000 ? "∞ (terms exact)" : reps} | ${f3(res.predictedObservedR)} | ${f3(res.meanObservedR)} | ${f3(res.power)} (${res.nSim}) |`);
}
say();
const att = roundRobinAttenuation({ groupSize: 6, nGroups: 80, r: 0.3, reps: 2, nSim: 120, seed: 41 });
say(`Removing member terms by two-way centring inside round-robin groups of ${att.groupSize} (r = ${att.r}, two replicates): predicted from reliability ${f3(att.predictedFromReliability)}, observed after centring **${f3(att.observedCentred)}**, observed on raw responses ${f3(att.observedRaw)}. The centring's own error attenuates further than the reliability alone, so the paper's line is a lower bound on the pairs a real design needs.`);
say();

// ── G6 §3 ──
say("## G6 §3 — distance validity as a concordance");
say();
const popE = populationConcordance({ space: "euclid", n: 1500, noise: 1, seed: 51 });
const popC = populationConcordance({ space: "criterion", n: 1500, noise: 1, seed: 51 });
say(`Population values at target noise 1 (n = 1500, sampled pair-pairs): Euclidean distance in the true latent space ${f3(popE)}; the criterion distance (between predictive means) ${f3(popC)}. The criterion is the ceiling a validated metric approaches; an isotropic metric on the same coordinates is below it.`);
say();
say("### The interval: units, not pairs");
say();
say("| n | Reps | Truth | Mean C | Empirical SD | Mean jackknife SE (units) | Mean bootstrap SE (pairs) | Jackknife coverage | Pair-bootstrap coverage |");
say("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
for (const n of [20, 40, 80]) {
  const res = coverageExperiment({ n, reps: 100, noise: 1, seed: 61 + n, truth: popE, B: 80 });
  say(`| ${n} | ${res.reps} | ${f3(res.truth)} | ${f3(res.meanC)} | ${f3(res.empiricalSD)} | ${f3(res.meanJackknifeSE)} | ${f3(res.meanPairBootstrapSE)} | ${f3(res.jackknifeCoverage)} | ${f3(res.pairBootstrapCoverage)} |`);
}
say();
say("### Spread against n");
say();
say("| n | Pairs | SD of C |");
say("| --- | --- | --- |");
const scaling = seScaling({ ns: [16, 32, 64, 128, 256], reps: 60, seed: 71 });
for (const row of scaling) say(`| ${row.n} | ${row.pairs} | ${f3(row.sd)} |`);
const r1 = scaling[0].sd / scaling[scaling.length - 1].sd;
say();
say(`From n = 16 to n = 256 the SD falls by a factor ${f3(r1)}; units^-1/2 predicts 4, pairs^-1/2 would predict about 16. The effective sample size is the units. Unit-level kernel variance (n · SE²) at n = 40: see the jackknife column above times n.`);
say();
say("### The ceiling");
say();
say("| Target noise | Criterion concordance | Euclidean-in-z concordance |");
say("| --- | --- | --- |");
for (const row of ceilingCurve({ noises: [0, 0.25, 0.5, 1, 2, 4], n: 400, seed: 81 })) say(`| ${row.noise} | ${f3(row.criterion)} | ${f3(row.euclid)} |`);
say();
say("### Shrinkage");
say();
const sh = shrinkageExperiment({ n: 60, reps: 40, seed: 91, obsNoise: 1.5 });
say("| Placement used for the distance | Mean concordance | SD |");
say("| --- | --- | --- |");
for (const [k, v] of Object.entries(sh)) say(`| ${k} | ${f3(v.mean)} | ${f3(v.sd)} |`);
say();
say("Units observed one to eight times with measurement noise 1.5 on each coordinate; the posterior mean shrinks toward the origin by k/(k+σ²). Read against G6 §3, which says a distance between shrunken point summaries understates the distance between sparsely observed units and biases the validity: the table says which direction, and by how much against the expected posterior distance.");
say();
say("### Resolving a difference between two spaces on the same pairs");
say();
const sz = sizingDifference({ n: 80, reps: 60, seed: 101 });
say(`At n = ${sz.n} the concordance difference between the true space and a noisy placement of it has mean ${f3(sz.meanDifference)} and SD ${f3(sz.sdDifference)} across draws. Scaling as units^-1/2, the units that put 2.8·SD at a stated difference:`);
say();
say("| Difference to resolve | Units co-observed on the target |");
say("| --- | --- |");
for (const row of sz.unitsNeeded) say(`| ${row.delta} | ${row.units} |`);
say();
say("Read against G6 §3's \"a difference of one hundredth of concordance takes units in the low thousands\".");
say();

const text = out.join("\n") + "\n";
process.stdout.write(text);
if (process.argv.includes("--write")) writeFileSync(join(here, "REPORT.md"), text);
